---
sidebar: sidebar 
permalink: access-data.html 
keywords: access data, mount point, mount volumes, mount clients, on-premises 
summary: Você pode acessar seus sistemas de arquivos FSX for ONTAP no local, montando volumes para clientes nas e montando LUNs iSCSI para clientes SAN. 
---
= Acesse seus dados do sistema de arquivos FSX for ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Você pode acessar seus sistemas de arquivos FSX for ONTAP no local, montando volumes para clientes nas e montando LUNs iSCSI para clientes SAN.

link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/supported-fsx-clients.html["Acesso aos dados"^] Na documentação do Amazon FSX for NetApp ONTAP, você encontrará tópicos sobre como acessar dados para sua referência.

Você também pode obter o ponto de montagem para volumes no workload da BlueXP  de fábrica.



== Obter ponto de montagem para volumes no workload da BlueXP  de fábrica

Obtenha o ponto de montagem de um volume para montar um compartilhamento em um compartilhamento CIFS ou cliente NFS.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos com o volume e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. Na guia volumes, selecione o menu de três pontos para o volume, depois *ações básicas* e, em seguida, *View mount command*.
. Na caixa de diálogo montar comando, selecione *Copiar* para copiar o comando. Você vai inserir o comando copiado no seu terminal.
. Selecione *Fechar*.




== Conete-se a clientes nas

* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-linux-client.html["Monte um volume em clientes Linux"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-windows-client.html["Montar um volume em clientes Windows"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/attach-mac-client.html["Monte um volume em clientes macOS"^]




== Conete-se a clientes SAN

* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/mount-iscsi-luns-linux.html["Montar um iSCSI LUN em clientes Linux"^]
* link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/mount-iscsi-windows.html["Montar um iSCSI LUN em clientes Windows"^]

