---
sidebar: sidebar 
permalink: cascade-replication.html 
keywords: replicate, cascade, cascade replication, cascade deployment, data protection, volume replication, replicate data protection volume 
summary: Replique volumes de proteção de dados, ou faça cascata na replicação de dados de volume, para estender a proteção de dados para sistemas terciários ou migrar seus dados. 
---
= Replique volumes de proteção de dados na fábrica de workloads da BlueXP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Replique volumes de proteção de dados, ou faça cascata na replicação de dados de volume, para estender a proteção de dados para sistemas terciários ou migrar seus dados.

.Sobre esta tarefa
A fábrica de workloads do BlueXP  dá suporte à replicação de volumes de proteção de dados, também chamados de _implantações em cascata_. Uma implementação de _cascata_ consiste em uma cadeia de relacionamentos em que um volume de origem é espelhado para um volume secundário (primeiro salto), e o volume secundário é espelhado para um volume terciário (segundo salto). Se o volume secundário ficar indisponível, é possível sincronizar a relação entre os volumes primário e terciário sem efetuar uma nova transferência de linha de base.

Esse recurso é compatível com o FSX para sistemas de arquivos ONTAP com o ONTAP versão 9,6 e posterior. link:https://docs.netapp.com/us-en/ontap/data-protection/compatible-ontap-versions-snapmirror-concept.html#snapmirror-disaster-recovery-relationships["Documentação do ONTAP para versões compatíveis do ONTAP"^]Consulte a .

Saiba mais link:https://docs.netapp.com/us-en/ontap/data-protection/supported-deployment-config-concept.html#how-cascade-deployments-work["como as implantações em cascata funcionam"^]sobre o .

.Antes de começar
Considere o seguinte antes de começar:

* Esteja ciente de que os volumes que fazem parte de uma configuração em cascata podem levar mais tempo para ressincronizar.
* Se o volume de origem da relação for um volume de proteção de dados e for um alvo de outra relação, reverter a relação de replicação não é suportado.
* É suportada uma réplica de um volume de proteção de dados (ou um segundo salto). Não é considerada prática recomendada criar uma segunda réplica de um volume de proteção de dados (ou um terceiro salto).


.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos que contém o(s) volume(s) para replicar e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. Na tabela volumes, selecione um ou mais volumes de proteção de dados (DP/volumes replicados) e, em seguida, selecione *replique dados*.
. Na página replicar dados, em destino replicação, forneça o seguinte:
+
.. *FSX para sistema de arquivos ONTAP*: Selecione credenciais, região e nome do sistema de arquivos FSX for ONTAP para o sistema de arquivos FSX for ONTAP de destino.
.. *Nome da VM de armazenamento*: Selecione a VM de armazenamento no menu suspenso.
.. *Nome do volume*: O nome do volume de destino é gerado automaticamente com o seguinte `{OriginalVolumeName}_copy` formato . Pode utilizar o nome do volume gerado automaticamente ou introduzir outro nome de volume.
.. *Caso de uso*: Selecione um dos seguintes casos de uso para a replicação. Dependendo do caso de uso selecionado, a fábrica de carga de trabalho preenche o formulário com os valores recomendados de acordo com as práticas recomendadas. Você pode aceitar os valores recomendados ou fazer alterações ao preencher o formulário.
+
*** Migração: Transfere seus dados para o sistema de arquivos FSX for ONTAP de destino
*** Recuperação de desastres quentes: Garante alta disponibilidade e recuperação rápida de desastres para cargas de trabalho críticas
*** Recuperação de desastres fria ou arquivada:
+
**** Recuperação de desastres inativos: Usa objetivos de tempo de recuperação (rto) mais longos e objetos de ponto de recuperação (RPO) para reduzir custos
**** Arquivamento: Replica dados para storage e conformidade de longo prazo


*** Outros


.. *Política de disposição em categorias*: Selecione a política de disposição em categorias para os dados armazenados no volume de destino. A política de disposição em categorias padrão é a política de disposição em categorias recomendada para o caso de uso selecionado.
+
_Balanced (Auto)_ é a política de disposição em camadas padrão ao criar um volume usando o console de fábrica da carga de trabalho. Para obter mais informações sobre políticas de disposição em camadas de volume, consulte a link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidade de armazenamento de volume"^]documentação do AWS FSX for NetApp ONTAP. Observe que a fábrica do workload usa nomes baseados em casos de uso no console de fábrica de carga de trabalho para políticas de disposição em camadas e inclui nomes de políticas de disposição em camadas do FSX for ONTAP entre parênteses.

+
Se você selecionou o caso de uso de migração, a fábrica de workload selecionará automaticamente para copiar a política de disposição em categorias do volume de origem para o volume de destino. Você pode desmarcar a opção para copiar a política de disposição em camadas e selecionar uma política de disposição em camadas que se aplique ao volume selecionado para replicação.

.. *Taxa máxima de transferência*: Selecione *limitada* e insira o limite máximo de transferência em MB/s. Em alternativa, selecione *Unlimited*.
+
Sem um limite, o desempenho da rede e do aplicativo pode declinar. Como alternativa, recomendamos uma taxa de transferência ilimitada para os sistemas de arquivos FSX for ONTAP para cargas de trabalho críticas, por exemplo, aquelas que são usadas principalmente para recuperação de desastres.



. Em Configurações de replicação, forneça o seguinte:
+
.. *Intervalo de replicação*: Selecione a frequência em que os instantâneos são transferidos do volume de origem para o volume de destino.
.. *Retenção de longo prazo*: Opcionalmente, habilite snapshots para retenção de longo prazo. A retenção de longo prazo permite que os serviços empresariais continuem operando mesmo em caso de falha completa do local, dando suporte ao failover de aplicações de forma transparente, usando uma cópia secundária.
+
Replicações sem retenção de longo prazo usam a política _MirrorAllSnapshots_. Habilitar a retenção de longo prazo atribui a política _MirrorAndVault_ à replicação.

+
Se você habilitar a retenção a longo prazo, selecione uma política existente ou crie uma nova política para definir os snapshots a serem replicados e o número a ser retido.

+

NOTE: Rótulos de origem e destino correspondentes são necessários para retenção a longo prazo. Se desejar, a fábrica Workload pode criar rótulos ausentes para você.

+
*** *Escolha uma política existente*: Selecione uma política existente no menu suspenso.
*** *Crie uma nova política*: Forneça o seguinte:
+
**** *Nome da política*: Insira um nome de política.
**** Opcional: Ativar instantâneos imutáveis.
+
***** Selecione *Ativar instantâneos imutáveis* para evitar que os instantâneos obtidos nesta política sejam excluídos durante o período de retenção.
***** Defina o *período de retenção* em número de horas, dias, meses ou anos.


**** *Políticas de snapshot*: Na tabela, selecione a frequência da política de snapshot e o número de cópias a reter. Pode selecionar mais de uma política de instantâneos.






. Selecione *criar*.


.Resultado
O volume ou volumes replicados replicam e aparecem na guia *relacionamentos de replicação* no sistema de arquivos FSX for ONTAP de destino.
