---
sidebar: sidebar 
permalink: configuration-analysis.html 
keywords: configuration issues, issues, improve, analyze, storage configuration, Amazon FSx for NetApp ONTAP, FSx for ONTAP, recommendation, recommendations 
summary: NetApp Workload Factory analisa regularmente as configurações do sistema de arquivos Amazon FSx for NetApp ONTAP para determinar se há algum problema de configuração. 
---
= Análise de configuração para sistemas de arquivos FSX for ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
NetApp Workload Factory analisa regularmente as configurações do sistema de arquivos Amazon FSx for NetApp ONTAP para determinar se há algum problema de configuração. Quando problemas são encontrados, Workload Factory mostra quais são os problemas e explica o que precisa ser alterado para garantir que o armazenamento do seu sistema de arquivos atinja desempenho máximo, eficiência de custos e conformidade com as melhores práticas.

Os principais recursos incluem:

* Análise de configuração diária
* Validações automáticas de melhores práticas
* Observabilidade proativa
* Insights para ação
* Consultor do AWS Well-Architected Framework




[[how-it-works]]
== Como funciona

O Workload Factory analisa diariamente suas cargas de trabalho em execução em implantações de sistemas de arquivos Amazon FSx for NetApp ONTAP. A análise fornece status bem arquitetado, insights e recomendações.

Após a conclusão da análise diária, as configurações aparecem como "otimizadas" ou "não otimizadas" no painel Well-architected da implantação. Você encontrará a pontuação total de otimização, problemas de configuração por categoria e uma lista de problemas de configuração e recomendações. Você pode revisar as recomendações para problemas de configuração. Alguns problemas podem ser corrigidos automaticamente pelo Workload Factory, enquanto outros exigem intervenção manual. Nesse caso, o Workload Factory fornece instruções detalhadas para ajudar você a implementar as alterações recomendadas.

Você pode descartar a análise de configurações que não se aplicam aos seus ambientes. Isso evita alertas desnecessários e resultados de otimização imprecisos.

Você também pode criar regras personalizadas em linguagem simples para validar seus ambientes em relação aos padrões da sua organização e às melhores práticas da NetApp. Teste as regras com uma simulação e, em seguida, agende a execução delas em todos os seus ambientes. link:https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["Saiba mais sobre regras personalizadas"^].

Você também pode criar regras personalizadas em linguagem simples para validar seus ambientes em relação aos padrões da sua organização e às melhores práticas da NetApp. Teste as regras com uma simulação e, em seguida, agende a execução delas em todos os seus ambientes.

link:https://docs.netapp.com/us-en/console-well-architected/learn-custom-rules.html["Saiba mais sobre regras personalizadas"^].



[[why-it-matters]]
== Por que isso importa

O Workload Factory aplica as melhores práticas a grandes ambientes de armazenamento, banco de dados e VMware, combinando avaliação contínua com insights de recomendações e remediação. As correções automatizadas aplicadas no console do Workload Factory reduzem erros humanos, garantem gerenciamento uniforme e preservam o desempenho e a confiabilidade em toda a sua infraestrutura de cargas de trabalho.



[[analysis-requirements]]
== Requisitos de análise

Para uma análise completa do sistema de arquivos, você deve fazer o seguinte:

* Associe um link.  A conectividade de link permite que o Workload Factory analise todas as configurações do sistema de arquivos, como proteção de dados e desempenho.
+
link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda como associar um link existente ou criar e associar um novo link"].

* Conceda permissões de _visualização, planejamento e análise_ em sua conta da AWS.
+
link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Saiba como conceder permissões a uma conta da AWS"^]





[[best-practices-and-recommendations-for-storage-workloads]]
== Melhores práticas e recomendações para cargas de trabalho de storage

O painel de arquitetura bem projetada avalia as configurações de storage em relação às melhores práticas do ONTAP e ao AWS Well-Architected Framework. A avaliação também recomenda melhorias e correções.

A análise bem arquitetada categoriza as configurações nos seguintes pilares da estrutura: _confiabilidade_, _segurança_, _excelência operacional_, _otimização de custos_ e _eficiência de desempenho_.



[[reliability]]
=== Confiabilidade

A confiabilidade garante que as workloads executem suas funções pretendidas de forma correta e consistente, mesmo quando ocorrem interrupções.

* *Backups de volume*
+
Fazer backup dos seus volumes ajuda a atender às necessidades de retenção de dados e conformidade. Use backups de volume para configurar backups automatizados e retenção para seus dados.

* *política do Snapshot*
+
Agende snapshots locais para backup eficiente e restaurações rápidas. Snapshots são imagens instantâneas de ponto no tempo dos seus volumes. Esta recomendação não se aplica a ambientes de banco de dados.

* *Instantâneos consistentes com a aplicação*
+
Para ambientes de banco de dados, use snapshots consistentes com o aplicativo NetApp SnapCenter para criar snapshots precisos e confiáveis dos seus dados de volume em um momento específico. Isso mantém seus aplicativos funcionando sem problemas e seus dados seguros. SnapCenter facilita o backup e ajuda você a restaurar dados de forma rápida e correta, reduzindo o tempo de inatividade e protegendo suas cargas de trabalho mais importantes.

* *Replicação entre regiões*
+
A replicação entre regiões garante que seus dados sejam replicados para outra região da AWS, proporcionando maior durabilidade e disponibilidade dos dados. Configure a replicação entre regiões para dar suporte à recuperação de desastres e conformidade.

* *Espaço livre de capacidade de SSD*
+
A capacidade da camada de armazenamento SSD não deve exceder 80% de utilização. Isso pode afetar as operações de leitura e gravação de dados na camada de armazenamento do seu pool de capacidade e impactar a taxa de transferência do seu sistema de arquivos. Quando a capacidade se esgota, os volumes de dados tornam-se somente leitura. Os serviços que tentam gravar novos dados também falham.

* *Rótulos de política de replicação*
+
Os rótulos da política de snapshot do volume de origem e os rótulos da política de replicação devem corresponder para garantir a confiabilidade dos dados.

* *Capacidade de objeto de arquivo*
+
O limite de capacidade de arquivos deve ser aumentado para evitar atingir o limite de capacidade do volume. A baixa capacidade de arquivos (inodes) impede a gravação de dados adicionais no volume. A Workload Factory recomenda manter a utilização da capacidade de arquivos abaixo de 80% para permitir a criação de novos arquivos.





[[security]]
=== Segurança

A segurança enfatiza proteger dados, sistemas e ativos por meio de avaliações de risco e estratégias de mitigação.

* *Proteção contra ransomware (ARP/AI)*
+
NetApp Autonomous Ransomware Protection com IA (ARP/AI) ajuda a proteger seus volumes contra ameaças de ransomware. Workload Factory recomenda habilitar ARP/AI para todos os volumes.

* *Acesso não autorizado ao volume iSCSI*
+
Volumes que servem dados de aplicativos usando iSCSI não devem permitir acesso NAS simultaneamente. A Workload Factory recomenda restringir volumes iSCSI de usarem qualquer outro protocolo.





[[operational-excellence]]
=== Excelência operacional

A excelência operacional concentra-se em fornecer a arquitetura mais ideal e valor comercial.

* *gerenciamento de capacidade automático*
+
O gerenciamento de capacidade automático deve ser ativado para garantir regularmente que a camada SSD não exceda o limite.

* *Folga de capacidade do volume*
+
A Workload Factory recomenda que a capacidade do volume não exceda 80% de utilização. Isso pode afetar as operações de leitura e gravação de dados em seu aplicativo. O aumento da capacidade do volume pode ser manual ou automático, utilizando o recurso volume com crescimento automático.

* *FlexCache modo de escrita*
+
Para um desempenho ideal, Workload Factory recomenda o modo de gravação de relacionamento de cache que melhor se adapta à sua carga de trabalho. O modo write-around oferece melhor desempenho para cargas de trabalho com muitas leituras e arquivos pequenos, enquanto o modo write-back oferece melhor desempenho para cargas de trabalho com muitas gravações e arquivos grandes.

* *FlexCache tamanho da réplica*
+
A NetApp Workload Factory recomenda ativar o dimensionamento automático e a limpeza em volumes de cache para manter o tamanho ideal e concentrar o cache nos dados mais acessados, visando eficiência máxima.

* *Relatórios de capacidade visíveis para o host*
+
A Workload Factory recomenda ativar os relatórios de capacidade visíveis ao host para fornecer melhor visibilidade do uso de storage no nível do volume.

* *Tipo de sistema operacional (SO)*
+
A Workload Factory recomenda garantir que o valor do tipo de sistema operacional (SO) do LUN ONTAP em ONTAP corresponda ao esquema de particionamento do sistema operacional para obter o alinhamento de E/S. Uma configuração incorreta pode reduzir o desempenho.

* *gerenciamento de espaço do dispositivo de bloco*
+
A Workload Factory recomenda configurar as definições de espaço em bloco para LUNs usados por instâncias de host de banco de dados para evitar falhas de gravação e melhorar a eficiência de espaço no FSx para ONTAP. Essa configuração se aplica à combinação recomendada de definições para volumes com thin provisioning: reserva de espaço, alocação de espaço e reserva fracionária.

* *thin provisioning*
+
A Workload Factory recomenda configurar thin provisioning para volumes FSx for ONTAP que hospedam instâncias de banco de dados. Essa abordagem permite armazenar mais dados lógicos do que os fisicamente disponíveis.





[[cost-optimization]]
=== Otimização de custos

A otimização de custos ajuda você a obter o máximo valor para o seu negócio enquanto mantém os custos baixos.

* *Tierização de dados frios*
+
Habilite o armazenamento em camadas de dados frios para reduzir a utilização da camada de armazenamento SSD. O Workload Factory recomenda aplicar uma política de armazenamento em camadas a cada volume focado em storage. Para volumes de banco de dados, vamos recomendar habilitar o armazenamento em camadas de dados frios quando apropriado. O FSx for ONTAP verifica continuamente os dados em busca de dados frios e os move para a camada do pool de capacidade sem interrupção.

* *Eficiências de storage*
+
Habilite as eficiências de armazenamento — compactação, compressão e deduplicação — para otimizar a utilização do storage e reduzir o custo da camada SSD.

* *Expiração do backup*
+
A Workload Factory recomenda excluir quaisquer backups criados manualmente para volumes que foram excluídos, bem como quaisquer backups com mais de duas semanas. Esses backups não expiram automaticamente, podem aumentar os custos e adicionar complexidade se você não precisar mais deles para SLA ou recuperação.

* *Expiração do Snapshot*
+
A Workload Factory recomenda excluir snapshots antigos ou criados manualmente que você não precisa mais. Removê-los pode reduzir custos e a desordem, especialmente se não forem necessários para seu SLA ou para suas necessidades de recuperação.

* *Dispositivos de bloco inativos*
+
Após um dispositivo de bloco não ser usado por sete dias, a Workload Factory recomenda arquivar os dados do dispositivo de bloco ou excluir o dispositivo de bloco não utilizado para reduzir custos.

* *Capacidade SSD superdimensionada*
+
Um nível de capacidade SSD superdimensionado adiciona custos desnecessários. A Workload Factory recomenda reduzir a capacidade da camada de SSD, mantendo um buffer de espaço livre de 20%. Uma operação de redução leva de algumas horas a vários dias, e outras operações do sistema de arquivos ficam indisponíveis durante esse período.

* *Volumes NAS inativos*
+
A análise de configuração identifica volumes NAS que não estão sendo usados ativamente e recomenda a exclusão ou arquivamento desses volumes para reduzir custos.





[[performance-efficiency]]
=== Eficiência de desempenho

A eficiência de desempenho ajuda você a garantir que seus recursos de storage sejam usados de forma eficaz e que as cargas de trabalho tenham desempenho ideal.

* *FlexGroup volumes reequilíbrio*
+
A Workload Factory recomenda o rebalanceamento dos seus volumes FlexGroup para melhorar a eficiência. Após a expansão horizontal, a capacidade e a atividade da carga de trabalho podem ficar desiguais entre os volumes.

* *FlexVol volumes reequilibrados*
+
A Workload Factory recomenda o rebalanceamento dos seus volumes FlexVol para melhorar a eficiência. Após a expansão horizontal, a capacidade e a atividade da carga de trabalho podem ficar desiguais entre os volumes.



.O que vem a seguir
link:improve-configurations.html["Implemente configurações de sistema de arquivos bem arquitetadas"]
