---
sidebar: sidebar 
permalink: create-replication.html 
keywords: replication, replicate 
summary: Crie uma relação de replicação para um sistema de arquivos FSX for ONTAP para evitar a perda de dados em caso de um desastre inesperado. 
---
= Criar uma relação de replicação na fábrica de workloads do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Crie uma relação de replicação para um sistema de arquivos FSX for ONTAP na fábrica de cargas de trabalho do BlueXP  para evitar a perda de dados em caso de um desastre inesperado.

.Sobre esta tarefa
A replicação é uma camada adicional de proteção de dados que é essencial para o caso de uma região onde seus dados residem sofrer um desastre. A perda de dados pode ser evitada se você usar replicação entre regiões.

Essa operação cria uma relação de replicação para um ou todos os volumes de origem em um sistema de arquivos FSX for ONTAP.

Os volumes replicados no sistema de arquivos de destino são volumes de proteção de dados (DP) e seguem o formato de nomenclatura: `{OriginalVolumeName}_copy`.

.Antes de começar
Certifique-se de que cumpre os seguintes pré-requisitos antes de começar.

* Você precisa ter dois sistemas de arquivos disponíveis no inventário de storage para criar uma relação de replicação.
* Os dois sistemas de arquivos usados para a relação de replicação devem ter um link associado. Se os sistemas de arquivos não tiverem links existentes, link:create-link.html["primeiro crie um link"]. Para link:manage-links.html["associe um link"]nos sistemas de ficheiros, selecione *ligação associada* em *Nome da conta*. Quando o link se associar em ambos os sistemas de arquivos, retorne a esta operação.


Siga as etapas a seguir para replicar volumes selecionados ou replicar todos os volumes em um sistema de arquivos.

É possível replicar um volume de origem (leitura/gravação) ou um volume de proteção de dados (DP). A replicação em cascata é compatível, mas um terceiro salto não é. Saiba mais link:https://review.docs.netapp.com/us-en/workload-fsx-ontap_cascade-replication/cascade-replication.html["replicação em cascata"^]sobre o .

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos que contém o(s) volume(s) para replicar e selecione *Gerenciar*.
. Replique todos os volumes em um sistema de arquivos ou replique volumes selecionados.
+
** Para replicar todos os volumes em um sistema de arquivos: Na visão geral do sistema de arquivos, selecione *replique dados*.
** Para replicar volumes selecionados: Na visão geral do sistema de arquivos, selecione a guia *volumes*.
+
Na tabela volumes, selecione um ou mais volumes e, em seguida, selecione *replique dados*.



. Na página replicar dados, em destino replicação, forneça o seguinte:
+
.. *FSX para sistema de arquivos ONTAP*: Selecione credenciais, região e nome do sistema de arquivos FSX for ONTAP para o sistema de arquivos FSX for ONTAP de destino.
.. *Nome da VM de armazenamento*: Selecione a VM de armazenamento no menu suspenso.
.. *Nome do volume*: O nome do volume de destino é gerado automaticamente com o seguinte `{OriginalVolumeName}_copy` formato . Pode utilizar o nome do volume gerado automaticamente ou introduzir outro nome de volume.
.. *Caso de uso*: Selecione um dos seguintes casos de uso para a replicação. Dependendo do caso de uso selecionado, a fábrica de carga de trabalho preenche o formulário com os valores recomendados de acordo com as práticas recomendadas. Você pode aceitar os valores recomendados ou fazer alterações ao preencher o formulário.
+
*** Migração: Transfere seus dados para o sistema de arquivos FSX for ONTAP de destino
*** Recuperação de desastres quentes: Garante alta disponibilidade e recuperação rápida de desastres para cargas de trabalho críticas
*** Recuperação de desastres fria ou arquivada:
+
**** Recuperação de desastres inativos: Usa objetivos de tempo de recuperação (rto) mais longos e objetos de ponto de recuperação (RPO) para reduzir custos
**** Arquivamento: Replica dados para storage e conformidade de longo prazo


*** Outros
+
Além disso, a seleção de caso de uso determina a política de replicação ou a política de SnapMirror (ONTAP). Os termos usados para descrever políticas de replicação vêm link:https://docs.netapp.com/us-en/ontap/data-protection/default-protection-policies-concept.html["Documentação do ONTAP 9"^]do .

+
**** Para migração e outros, a política de replicação é chamada _MirrorAllSnapshots_. _MirrorAllSnapshots_ é uma política assíncrona para espelhar todos os snapshots e o sistema de arquivos ativo mais recente.
**** Para recuperação de desastres de arquivos, inativos ou quentes, a política de replicação é chamada _MirrorAndVault_. _MirrorAndVault_ é uma política assíncrona e de cofre para espelhar o mais recente sistema de arquivos ativo e instantâneos diários e semanais.
+
Para todos os casos de uso, se você habilitar snapshots para retenção de longo prazo, a política de replicação padrão é _MirrorAndVault_.





.. *Política de disposição em categorias*: Selecione a política de disposição em categorias para os dados armazenados no volume de destino. A política de disposição em categorias padrão é a política de disposição em categorias recomendada para o caso de uso selecionado.
+
_Balanced (Auto)_ é a política de disposição em camadas padrão ao criar um volume usando o console de fábrica da carga de trabalho. Para obter mais informações sobre políticas de disposição em camadas de volume, consulte a link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidade de armazenamento de volume"^]documentação do AWS FSX for NetApp ONTAP. Observe que a fábrica do workload usa nomes baseados em casos de uso no console de fábrica de carga de trabalho para políticas de disposição em camadas e inclui nomes de políticas de disposição em camadas do FSX for ONTAP entre parênteses.

+
Se você selecionou o caso de uso de migração, a fábrica de workload selecionará automaticamente para copiar a política de disposição em categorias do volume de origem para o volume de destino. Você pode desmarcar a opção para copiar a política de disposição em camadas e selecionar uma política de disposição em camadas que se aplique ao volume selecionado para replicação.

.. *Taxa máxima de transferência*: Selecione *limitada* e insira o limite máximo de transferência em MB/s. Em alternativa, selecione *Unlimited*.
+
Sem um limite, o desempenho da rede e do aplicativo pode declinar. Como alternativa, recomendamos uma taxa de transferência ilimitada para os sistemas de arquivos FSX for ONTAP para cargas de trabalho críticas, por exemplo, aquelas que são usadas principalmente para recuperação de desastres.



. Em Configurações de replicação, forneça o seguinte:
+
.. *Intervalo de replicação*: Selecione a frequência em que os instantâneos são transferidos do volume de origem para o volume de destino.
.. *Retenção de longo prazo*: Opcionalmente, habilite snapshots para retenção de longo prazo. A retenção de longo prazo permite que os serviços empresariais continuem operando mesmo em caso de falha completa do local, dando suporte ao failover de aplicações de forma transparente, usando uma cópia secundária.
+
Replicações sem retenção de longo prazo usam a política _MirrorAllSnapshots_. Habilitar a retenção de longo prazo atribui a política _MirrorAndVault_ à replicação.

+
Se você habilitar a retenção a longo prazo, selecione uma política existente ou crie uma nova política para definir os snapshots a serem replicados e o número a ser retido.

+

NOTE: Rótulos de origem e destino correspondentes são necessários para retenção a longo prazo. Se desejar, a fábrica Workload pode criar rótulos ausentes para você.

+
*** *Escolha uma política existente*: Selecione uma política existente no menu suspenso.
*** *Crie uma nova política*: Forneça o seguinte:
+
**** *Nome da política*: Insira um nome de política.
**** Opcional: Ativar instantâneos imutáveis.
+
***** Selecione *Ativar instantâneos imutáveis* para evitar que os instantâneos obtidos nesta política sejam excluídos durante o período de retenção.
***** Defina o *período de retenção* em número de horas, dias, meses ou anos.


**** *Políticas de snapshot*: Na tabela, selecione a frequência da política de snapshot e o número de cópias a reter. Pode selecionar mais de uma política de instantâneos.






. Selecione *criar*.


.Resultado
A relação de replicação aparece na guia *relacionamentos de replicação* no sistema de arquivos FSX for ONTAP de destino.
