---
sidebar: sidebar 
permalink: create-igroup.html 
keywords: create initiator group, create igroup, iscsi protocol 
summary: Crie grupos de iniciadores para gerenciar o acesso do host aos dispositivos de bloco no NetApp Workload Factory. 
---
= Crie um grupo de iniciadores para um sistema de arquivos no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Use NetApp Workload Factory para criar grupos de iniciadores e gerenciar o acesso do host aos dispositivos de bloco SAN.

.Sobre esta tarefa
Os grupos de iniciadores, ou igroups, conectam dispositivos de bloco (LUNs) aos recursos de computação que têm permissão para acessá-los. Ao contrário de NFS ou CIFS, onde um volume é amplamente acessível e as permissões do usuário controlam o acesso, as permissões de storage em bloco operam no nível da máquina. Normalmente, apenas um sistema pode acessar um dispositivo de bloco por vez.

Um igroup atua como uma camada de permissões para armazenamento em blocos. Quando um servidor se conecta ao sistema de storage, ele se identifica usando seu iniciador de host qualificado iSCSI (IQN). Se esse IQN pertencer a um ou mais igroups, então o servidor obterá acesso a todos os LUNs associados a esses igroups. Tanto um igroup quanto uma conexão de host iSCSI são necessários para que o iSCSI funcione corretamente.

.Antes de começar
Você deve associar um link para criar igroups. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda como associar um link existente ou criar e associar um novo link"]. Depois de associar o link, retorne a esta operação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx para ONTAP*, selecione a guia *Dispositivos de bloco*.
. Selecione o tipo de recurso *Create initiator group* e, em seguida, selecione *Create igroup*.
. Na caixa de diálogo *Criar grupo iniciador*, faça o seguinte:
+
** *igroup name*: Insira um nome para o grupo de iniciadores.
** *igroup description*: (Opcional) Insira uma descrição para o grupo iniciador.
** *Nome da VM de armazenamento*: selecione a VM de armazenamento para o grupo iniciador.
** *Nome do dispositivo de bloco*: selecione um ou mais dispositivos de bloco para associar ao grupo de iniciadores. Os dispositivos de bloco listados são aqueles que ainda não foram mapeados para um iniciador host.
** *Tipo de sistema operacional*: Selecione Linux, VMware ou Windows para o tipo de sistema operacional.
** *Iniciadores de host*: Adicione um ou mais iniciadores de host qualificados iSCSI (IQN) ao grupo de iniciadores.


. Selecione *criar*.


.Informações relacionadas
link:https://docs.netapp.com/us-en/workload-fsx-ontap/manage-igroups.html["Gerencie os igroups para um sistema de arquivos FSx for ONTAP"]
