---
sidebar: sidebar 
permalink: create-volume-from-snapshot.html 
keywords: create volume from snapshot, new volume 
summary: Crie um snapshot manual de um volume do FSX for ONTAP. Os instantâneos são versões pontuais do conteúdo do seu volume. 
---
= Crie um novo volume do FSX for ONTAP a partir de um snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Crie um novo volume do FSX for ONTAP a partir de um snapshot para permitir a recuperação pontual.

.Sobre esta tarefa
Um snapshot é uma imagem somente leitura de um volume do FSX for ONTAP tirada em um ponto no tempo. A criação de um novo volume a partir de um snapshot faz uma cópia de um volume inteiro em poucos segundos, independentemente do tamanho do volume. A cópia recém-criada representa um novo volume.

.Antes de começar
Considere as seguintes limitações antes de criar um volume a partir de um instantâneo:

* Alterações nos modelos de permissão: Se você usar essa operação para alternar o tipo de protocolo nas (Network-Attached Storage), ela também pode alternar o modelo de permissão fornecido pelo estilo de segurança. Você pode ter problemas de permissão de acesso a arquivos, que você só pode corrigir manualmente com acesso de administrador usando as ferramentas de cliente nas para configuração de permissões.
* Maior consumo de volume: Depois de criar um volume a partir de um snapshot, você terá dois volumes independentes e ambos consomem capacidade do sistema de arquivos do host.


.Passos
. Inicie sessão no link:https://console.workloads.netapp.com/["Console de fábrica da carga de trabalho"^]
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, clique no menu de três pontos do sistema de arquivos com o instantâneo de volume e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. Na guia volumes, clique no menu três pontos para o volume que tem o instantâneo do qual você deseja criar um volume.
. Selecione *ações de proteção de dados*, *instantâneos* e, em seguida, *criar um volume a partir de um instantâneo*.
. Na caixa de diálogo criar volume a partir de um instantâneo, introduza o nome do instantâneo.
. Clique em *criar*.

