---
sidebar: sidebar 
permalink: create-link.html 
keywords: connect, connection, link, lambda link, associate link, create link, authenticate link 
summary: Você pode criar e gerenciar links para fornecer um relacionamento de confiança e conectividade entre uma conta do NetApp Workload Factory e um ou mais sistemas de arquivos FSx para ONTAP . 
---
= Conete-se a um sistema de arquivos FSX for ONTAP com um link do Lambda
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Para executar operações avançadas de gerenciamento do ONTAP , configure uma conexão entre sua conta do Workload Factory e um ou mais sistemas de arquivos FSx for ONTAP . Isso envolve associar links Lambda novos e existentes e autenticar os links. A associação de links permite monitorar e gerencie determinados recursos diretamente do sistema de arquivos FSx for ONTAP que não estão disponíveis por meio da API do Amazon FSx for ONTAP .

link:links-overview.html["Saiba mais sobre links"].

.Sobre esta tarefa
Use o AWS Lambda para executar código em resposta a eventos e gerenciar automaticamente os recursos de computação exigidos por esse código. Os links que você cria fazem parte da sua conta do NetApp e são associados a uma conta da AWS.

Você pode criar um link em sua conta ao definir um FSx para o sistema de arquivos ONTAP .  O link é usado para esse sistema de arquivos e pode ser usado para outros sistemas de arquivos FSx for ONTAP .  Você também pode associar um link para um sistema de arquivos posteriormente.

Os links exigem autenticação. Você pode autenticar links usando credenciais armazenadas no serviço de credenciais do Workload Factory ou com suas credenciais armazenadas no AWS Secrets Manager. Apenas um método de autenticação é suportado por link. Por exemplo, se você selecionar a autenticação de link com o AWS Secrets Manager, não poderá alterar o método de autenticação posteriormente.


NOTE: O AWS Secrets Manager não é suportado ao usar um conetor.



== Associe um novo link

Associar um novo link inclui criação e associação de links.

Você tem duas opções para criar links neste fluxo de trabalho: automática ou manualmente. Você precisará iniciar uma pilha do AWS CloudFormation na sua conta da AWS para criar o link.

* Automaticamente: Cria um link com registro automático via Workload Factory.  Um link criado automaticamente requer tokens para automação do Workload Factory e o código do CloudFormation tem vida curta.  Ele só pode ser usado por até seis horas.
* Manualmente: cria um link com registro manual usando o CloudFormation ou o Terraform a partir do Codebox.  O código persiste, dando a você mais tempo para concluir a operação.  Isso é útil ao trabalhar com equipes diferentes, como Segurança e DevOps, que podem primeiro precisar conceder as permissões necessárias para concluir a criação do link.


.Antes de começar
* Você deve considerar qual opção de criação de link você usará.
* Você precisa ter pelo menos um sistema de arquivos FSx para ONTAP no Workload Factory.  Para descobrir sistemas de arquivos FSx para ONTAP , você precisa ter uma conta da AWS com permissões para instâncias do FSx para ONTAP .link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html#overview["adicionar credenciais no Workload Factory"^] Com permissões de _visualização, planejamento e análise_ para gerenciamento de armazenamento.
* As seguintes portas devem ser abertas no grupo de segurança associado ao sistema de arquivos FSx para ONTAP para conectividade de link.
+
** Para o console do Workload Factory: porta 443 (HTTPS)
** Para CloudShell: porta 22 (SSH)


* Você deve ter as seguintes permissões na sua conta da AWS ao adicionar um link usando uma pilha do CloudFormation:
+
[%collapsible]
====
[source, json]
----
"cloudformation:GetTemplateSummary",
"cloudformation:CreateStack",
"cloudformation:DeleteStack",
"cloudformation:DescribeStacks",
"cloudformation:ListStacks",
"cloudformation:DescribeStackEvents",
"cloudformation:ListStackResources",
"ec2:DescribeSubnets",
"ec2:DescribeSecurityGroups",
"ec2:DescribeVpcs",
"iam:ListRoles",
"iam:GetRolePolicy",
"iam:GetRole",
"iam:DeleteRolePolicy",
"iam:CreateRole",
"iam:DetachRolePolicy",
"iam:PassRole",
"iam:PutRolePolicy",
"iam:DeleteRole",
"iam:AttachRolePolicy",
"lambda:AddPermission",
"lambda:RemovePermission",
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:CreateFunction",
"lambda:DeleteFunction",
"lambda:TagResource",
"codestar-connections:GetSyncConfiguration",
"ecr:BatchGetImage",
"ecr:GetDownloadUrlForLayer"
----
====


[role="tabbed-block"]
====
.Criar automaticamente
--
Use o CloudFormation para criar e registrar automaticamente o link no Workload Factory.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos ao qual deseja associar um link e, em seguida, selecione *Associar link*.
. Na caixa de diálogo associar, selecione *criar um novo link* e selecione *continuar*.
. Na página criar link, forneça o seguinte:
+
.. *Link name*: Insira o nome que deseja usar para esse link. O nome deve ser exclusivo na sua conta.
.. *AWS Secrets Manager*: Opcional.  Permite que o Workload Factory busque credenciais de acesso do FSx para ONTAP no seu AWS Secrets Manager.
+
A pilha de implantação de links adiciona automaticamente o seguinte regex ARN do gerenciador de segredos padrão à política de permissão do Lambda: `arn:aws:secretsmanager:<link_deployment_region>:<link_deployment_account_id>:secret:FSxSecret*` .

+
Você pode criar segredos em alinhamento com as permissões padrão ou atribuir suas permissões personalizadas para a política de links.

+
*Configurar endpoint privado VPC para o AWS Secrets Manager* está desativado por padrão. Selecionar essa opção armazena o segredo usando o endpoint privado VPC em vez de armazená-lo localmente.

.. *Permissões de link*: Selecione uma das seguintes opções para permissões de link:
+
*** *Automático*: selecione esta opção para que o código do AWS CloudFormation crie automaticamente a política de permissão e a função de execução do Lambda.
*** *Fornecido pelo usuário*: Selecione esta opção para atribuir uma função de execução do Lambda específica e suas políticas anexadas ao link do Lambda. As seguintes permissões são necessárias para a política de permissões do Lambda .  `secretsmanager:GetSecretValue` a permissão será necessária somente se você tiver habilitado o AWS Secrets Manager.
+
[source, json]
----
"ec2:CreateNetworkInterface",
"ec2:DescribeNetworkInterfaces",
"ec2:DeleteNetworkInterface",
"ec2:AssignPrivateIpAddresses",
"ec2:UnassignPrivateIpAddresses",
"secretsmanager:GetSecretValue"
----
+
Insira o ARN da função de execução do Lambda na caixa de texto.



.. *Tags*: Opcionalmente, adicione quaisquer tags que você deseja associar a este link para que você possa categorizar mais facilmente seus recursos. Por exemplo, você pode adicionar uma tag que identifique esse link como sendo usado pelo FSX para sistemas de arquivos ONTAP.
+
O Workload Factory recupera automaticamente a conta, o local e o grupo de segurança da AWS com base no sistema de arquivos FSx para ONTAP .



. Selecione *criar*.
+
A caixa de diálogo Redirecionar para CloudFormation é exibida e explica como criar o link do serviço AWS CloudFormation.

. Selecione *continuar* para abrir o Console de Gerenciamento da AWS e, em seguida, faça login na conta da AWS para este sistema de arquivos FSX for ONTAP.
. Na página de pilha de criação rápida, em recursos, selecione *reconheço que o AWS CloudFormation pode criar recursos do IAM*.
+
Observe que três permissões são concedidas ao Lambda quando você inicia o modelo do CloudFormation. A fábrica de carga de trabalho usa essas permissões ao usar links.

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
. Selecione *criar pilha* e selecione *continuar*.
+
Você pode monitorar o status da criação do link na página Eventos.  Isso não deve levar mais de 5 minutos.

. Retorne à interface do Workload Factory e você verá que o link está associado ao sistema de arquivos FSx para ONTAP .


--
.Criar manualmente
--
Você pode criar um link usando duas ferramentas de Infraestrutura como Código (IaC) do Codebox: CloudFormation ou Terraform.  Com esta opção, você extrai o ARN do link do AWS CloudFormation e o informa aqui.  A fábrica de carga de trabalho registra manualmente o link para você.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos ao qual deseja associar um link e, em seguida, selecione *Associar link*.
. Na caixa de diálogo associar, selecione *criar um novo link* e selecione *continuar*.
. Na página Criar link, selecione CloudFormation ou Terraform na Caixa de código e forneça o seguinte:
+
.. *Link name*: Insira o nome que deseja usar para esse link. O nome deve ser exclusivo na sua conta.
.. *AWS Secrets Manager*: Opcional.  Permite que o Workload Factory busque credenciais de acesso do FSx para ONTAP no seu AWS Secrets Manager.
+
A pilha de implantação de links adiciona automaticamente o seguinte regex ARN do gerenciador de segredos padrão à política de permissão do Lambda: `arn:aws:secretsmanager:<link_deployment_region>:<link_deployment_account_id>:secret:FSxSecret*` .

+
Você pode criar segredos em alinhamento com as permissões padrão ou atribuir suas permissões personalizadas para a política de links.

+
*Configurar endpoint privado VPC para o AWS Secrets Manager* está desativado por padrão. Selecionar essa opção armazena o segredo usando o endpoint privado VPC em vez de armazená-lo localmente.

.. *Permissões de link*: Selecione uma das seguintes opções para permissões de link:
+
*** *Automático*: selecione esta opção para que o código do AWS CloudFormation crie automaticamente a política de permissão e a função de execução do Lambda.
*** *Fornecido pelo usuário*: Selecione esta opção para atribuir uma função de execução do Lambda específica e suas políticas anexadas ao link do Lambda. As seguintes permissões são necessárias para a política de permissões do Lambda .  `secretsmanager:GetSecretValue` a permissão será necessária somente se você tiver habilitado o AWS Secrets Manager.
+
[source, json]
----
"ec2:CreateNetworkInterface",
"ec2:DescribeNetworkInterfaces",
"ec2:DeleteNetworkInterface",
"ec2:AssignPrivateIpAddresses",
"ec2:UnassignPrivateIpAddresses"
"secretsmanager:GetSecretValue"
----
+
Insira o ARN da função de execução do Lambda na caixa de texto.



.. *Tags*: Opcionalmente, adicione quaisquer tags que você deseja associar a este link para que você possa categorizar mais facilmente seus recursos. Por exemplo, você pode adicionar uma tag que identifique esse link como sendo usado pelo FSX para sistemas de arquivos ONTAP.
.. *Registro de link*: Selecione CloudFormation ou Terraform para obter instruções sobre como registrar o link e siga as instruções.
+
Observe que três permissões são concedidas ao Lambda quando você inicia o modelo do CloudFormation. A fábrica de carga de trabalho usa essas permissões ao usar links.

+
[source, json]
----
"lambda:InvokeFunction",
"lambda:GetFunction",
"lambda:UpdateFunctionCode"
----
+
Depois de criar a pilha com êxito, cole o ARN do Lambda na caixa de texto.

.. O Workload Factory recupera automaticamente a conta, o local e o grupo de segurança da AWS com base no sistema de arquivos FSx para ONTAP .


. Selecione *criar*.
+
Você pode monitorar o status da criação do link na página Eventos.  Isso não deve levar mais de 5 minutos.

. Retorne à interface do Workload Factory e você verá que o link está associado ao sistema de arquivos FSx para ONTAP .


--
====
.Resultado
A fábrica de carga de trabalho associa o link ao sistema de arquivos FSx para ONTAP .  Você pode executar operações ONTAP avançadas.



== Associe um link existente com um sistema de arquivos FSX for ONTAP

Depois de criar um link, associe-o a um ou mais sistema de arquivos FSX for ONTAP.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos ao qual deseja associar um link e, em seguida, selecione *Associar link*.
. Na página associar link, selecione *associar um link existente*, selecione o link e selecione *continuar*.
. Selecione o modo de autenticação.
+
** Fábrica da carga de trabalho: Introduza a palavra-passe duas vezes.
** AWS Secrets Manager: Insira o ARN secreto.
+
Certifique-se de que o ARN secreto contém os seguintes pares de chaves válidos, embora o _filesystemID_ seja opcional.

+
*** filesystemID = FSx_filesystem_id (opcional)
*** usuário = FSx_user
*** palavra-passe: user_password
+

NOTE: A autenticação com o AWS Secrets Manager requer um usuário, o _FSx_user_ fornecido por você ou outro usuário criado no sistema de arquivos FSx para ONTAP .  O usuário padrão é `fsxadmin` se você não fornecer um usuário.





. Selecione *aplicar*.


.Resultado
O link está associado ao sistema de arquivos FSX for ONTAP. Você pode executar operações ONTAP avançadas.



== Solucionar problemas com a autenticação de link do AWS Secrets Manager

Problema:: O link não possui permissões para recuperar o segredo.
+
--
*Resolução*: Adicione permissões após o link estar ativo. Faça login no console da AWS, localize o link do Lambda e edite a política de permissão anexada.

--
Problema:: O segredo não é encontrado.
+
--
*Resolução*: Forneça o ARN secreto correto.

--
Problema:: O segredo não está no formato certo.
+
--
*Resolução*: Vá para o AWS Secrets Manager e edite o formato.

O segredo deve conter os seguintes pares de chaves válidos:

* O sistema de arquivos FSX_filesystem_id
* nome de usuário = FSx_user
* palavra-passe: user_password


--
Problema:: O segredo não contém credenciais ONTAP válidas para autenticação do sistema de arquivos.
+
--
* Resolução*: Forneça credenciais que podem autenticar o FSX para sistemas de arquivos ONTAP no AWS Secrets Manager.

--

