---
sidebar: sidebar 
permalink: create-snapshot.html 
keywords: create snapshot, snapshot 
summary: Crie um snapshot manual de um volume FSx para ONTAP no NetApp Workload Factory.  Snapshots são versões pontuais do conteúdo do seu volume. 
---
= Crie um snapshot manual de um volume do FSX for ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Crie um snapshot manual de um volume FSx para ONTAP no NetApp Workload Factory.  Snapshots são versões pontuais do conteúdo do seu volume.

Os snapshots são recursos de volumes e são capturas instantâneas de seus dados que consomem espaço apenas para dados modificados. Como os dados mudam com o tempo, os snapshots geralmente consomem mais espaço à medida que envelhecem.

O FSX para ONTAP volumes usa cópia-on-write just-in-time para que todos os arquivos não modificados em snapshots não consumam nenhuma capacidade do volume.


NOTE: Os snapshots não são cópias de seus dados. Se você quiser fazer cópias de seus dados, considere usar os backups do FSX for ONTAP ou os recursos de replicação de volume.

.Antes de começar
Você deve associar um link para criar um instantâneo manual de um volume. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda como associar um link existente ou criar e associar um novo link"]. Após os associados da ligação, volte a esta operação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos que contém o volume para criar um snapshot e então selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. Na aba *Volumes*, selecione o menu de ações para o volume a ser protegido com instantâneos.
. Selecione *Ações de proteção de dados* e depois *Gerenciar instantâneos*.
. Na página Gerenciar instantâneos, selecione *Criar instantâneo*.
. Na caixa de diálogo Criar um instantâneo, faça o seguinte:
+
.. Digite um nome de instantâneo no campo *Nome do instantâneo*.
.. Opcionalmente, selecione um rótulo ou crie um novo rótulo.
.. Defina o *período de retenção* como um número de horas, dias, meses ou anos.
.. Opcional: *Torne este snapshot imutável* para evitar que ele seja excluído durante o período de retenção.
+
Aceite a declaração sobre snapshots imutáveis.



. Selecione *criar*.

