---
sidebar: sidebar 
permalink: create-file-system.html 
keywords: create, FSx file system, ONTAP file system, Workload Factory, storage 
summary: Usando o NetApp Workload Factory, você pode criar um FSx para o sistema de arquivos ONTAP para adicionar e gerenciar volumes e serviços de dados adicionais. 
---
= Crie um sistema de arquivos FSx para ONTAP no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Usando o NetApp Workload Factory, você pode criar FSx de primeira e segunda geração para sistemas de arquivos ONTAP para adicionar e gerenciar volumes e serviços de dados adicionais.

.Sobre esta tarefa
Uma VM de storage e um grupo de segurança são criados como parte da criação do sistema de arquivos.

.Antes de começar
Antes de criar seu sistema de arquivos FSX for ONTAP, você precisará de:

* O ARN de uma função do IAM que concede ao Workload Factory as permissões necessárias para criar um sistema de arquivos FSx para ONTAP . link:https://docs.netapp.com/us-en/workload-setup-admin/add-credentials.html["Saiba como conceder permissões a uma conta da AWS"^] .
* A região e as informações de VPC para onde você criará a instância do FSX for ONTAP.




== Crie um sistema de arquivos FSX for ONTAP

Você pode criar um sistema de arquivos FSX for ONTAP usando _Quick Create_ ou _Advanced Create_. Você também pode usar as seguintes ferramentas disponíveis na Codebox: API REST, CloudFormation e Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Saiba como usar o Codebox para automação"^].


NOTE: Ao usar o Terraform do Codebox, o código que você copia ou baixa oculta `fsxadmin` e `vsadmin` senhas. Você precisará digitar novamente as senhas quando executar o código.

[role="tabbed-block"]
====
.Criação rápida
--
O Quick Create permite que você use uma configuração recomendada de práticas recomendadas. Você pode alterar a maioria das configurações depois de criar um sistema de arquivos FSX for ONTAP.

Os sistemas de arquivos FSx de segunda geração para ONTAP são o tipo de implantação padrão para criação rápida, a menos que a região selecionada não ofereça suporte aos sistemas de arquivos FSx de segunda geração para ONTAP.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Criar FSx para ONTAP*.
. Na página criar FSX para ONTAP, selecione *criar rápido*.
+
Você também pode carregar uma configuração salva.

. Em Configuração geral do sistema de arquivos, forneça o seguinte:
+
.. *Credenciais da AWS*: selecione para adicionar credenciais da AWS no Workload Factory ou continuar sem credenciais.
.. *Nome do sistema de arquivos*: Insira um nome para o sistema de arquivos.
.. *Região e VPC*: Selecione a região e a VPC para o sistema de arquivos.
.. *Tipo de implantação*: Selecione um tipo de implantação.
+
*** Implantação de zona única de disponibilidade (Single-AZ): Fornece disponibilidade monitorando falhas de hardware e substituindo automaticamente componentes de infraestrutura em caso de falha. Atinge alta durabilidade replicando automaticamente seus dados em uma zona de disponibilidade para protegê-los de falhas de componentes.
+
Essa configuração é recomendada para cargas de trabalho de alto desempenho ou quando as cargas de trabalho começam pequenas e aumentam gradualmente para 72 GB/s de taxa de transferência e 2,4 milhões de IOPS.

*** Implantação de várias zonas de disponibilidade (Multi-AZ): Fornece disponibilidade contínua aos dados, mesmo quando uma zona de disponibilidade não está disponível. Um sistema de arquivos Multi-AZ foi desenvolvido para workloads de produção essenciais aos negócios que exigem alta disponibilidade para dados de arquivos ONTAP compartilhados e precisam de storage com replicação incorporada entre zonas de disponibilidade.
+
Esta configuração de par HA único é recomendada para cargas de trabalho que exigem até 6 GB/s de taxa de transferência ou 200.000 IOPS.



.. *Tags*: Opcionalmente, você pode adicionar até 50 tags.


. Em *Detalhes do sistema de arquivos*, forneça o seguinte:
+
.. *Capacidade de armazenamento SSD*: Introduza a capacidade de armazenamento e selecione a unidade de capacidade de armazenamento.
+
*** Para implantações de primeira geração, não é possível diminuir a capacidade após a criação do sistema de arquivos.
*** Para implantações de segunda geração, você pode aumentar a capacidade após a criação do sistema de arquivos.


.. *Credenciais ONTAP*: Opcional. Introduza o nome de utilizador e a palavra-passe do ONTAP. A senha pode ser definida agora ou mais tarde.
+
Se o usuário que você fornecer não for o usuário fsxadmin, e mais tarde você precisar redefinir a senha do fsxadmin, você poderá fazer isso no console da AWS.

.. *Configuração SMB/CIFS*: Opcional. Se você planeja usar o protocolo SMB/CIFS para acessar volumes, configure o ative Directory para a VM de storage durante a criação do sistema de arquivos. Forneça os detalhes a seguir para a VM de storage criada para esse sistema de arquivos.
+
... *Domínio do ative Directory para ingressar*: Insira o nome de domínio totalmente qualificado (FQDN) para o ative Directory.
... *Endereços IP DNS*: Insira até três endereços IP DNS separados por vírgulas.
... *Nome NetBIOS do servidor SMB*: Insira o nome NetBIOS do servidor SMB do objeto computador do ative Directory a ser criado para sua VM de armazenamento. Este é o nome desta VM de armazenamento no ative Directory.
... *Nome de utilizador*: Introduza o nome de utilizador da conta de serviço no ative Directory existente.
+
Não inclua um prefixo ou sufixo de domínio. Para `EXAMPLE\ADMIN`, use `ADMIN`.

... *Senha*: Insira a senha da conta de serviço.
... * Unidade de organização*: Opcionalmente, insira o nome da Unidade organizacional onde você pretende criar a conta de computador para o FSX for ONTAP. A UO é o nome de caminho distinto da unidade organizacional à qual você deseja ingressar no sistema de arquivos.
... *Grupo de administradores delegados*: Opcionalmente, insira o nome do grupo no ative Directory que pode administrar seu sistema de arquivos.
+
Se você estiver usando o AWS Managed Microsoft AD, você deve especificar um grupo como Administradores delegados do FSX da AWS, Administradores delegados da AWS ou um grupo personalizado com permissões delegadas na UO.

+
Se você estiver se juntando a um AD autogerenciado, use o nome do grupo em seu AD. O grupo padrão é `Domain Admins`.





. Abra o *Summary* para rever a configuração definida. Se necessário, você pode alterar qualquer configuração neste momento antes de salvar ou criar o sistema de arquivos.
. Salve ou crie o sistema de arquivos.


Se você criou o sistema de arquivos, agora você pode visualizar o sistema de arquivos FSX for ONTAP na página *Inventário*.

--
.Criação avançada
--
Com o Advanced Create, você define todas as opções de configuração, incluindo disponibilidade, segurança, backups e manutenção.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Criar FSx para ONTAP*.
. Na página criar FSX para ONTAP, selecione *criar avançado*.
+
Você também pode carregar uma configuração salva.

. Em Configuração geral do sistema de arquivos, forneça o seguinte:
+
.. *Credenciais da AWS*: selecione para adicionar credenciais da AWS no Workload Factory ou continuar sem credenciais.
.. *Nome do sistema de arquivos*: Insira um nome para o sistema de arquivos.
.. *Região e VPC*: Selecione a região e a VPC para o sistema de arquivos.
.. *Tipo de implantação*: Selecione um tipo de implantação e geração de sistema de arquivos. A disponibilidade de um sistema de arquivos de segunda geração depende da região selecionada. Se a região selecionada não oferecer suporte ao FSx de segunda geração para sistemas de arquivos ONTAP, o tipo de implantação mudará para a primeira geração.
+
*** Implantação de zona única de disponibilidade (Single-AZ): Fornece disponibilidade monitorando falhas de hardware e substituindo automaticamente componentes de infraestrutura em caso de falha. Atinge alta durabilidade replicando automaticamente seus dados em uma zona de disponibilidade para protegê-los de falhas de componentes.
+
*Geração do sistema de arquivos*: Selecione uma das seguintes opções:

+
**** *Segunda geração*: esta configuração é recomendada para cargas de trabalho de alto desempenho ou quando as cargas de trabalho começam pequenas e aumentam gradualmente para 72 GB/s de taxa de transferência e 2,4 milhões de IOPS.
**** *Primeira geração*: Esta configuração é ideal para cargas de trabalho que exigem até 4 GB/s ou 160.000 IOPS. Os sistemas de arquivos de primeira geração podem apenas aumentar a capacidade.


*** Implantação de várias zonas de disponibilidade (Multi-AZ): Fornece disponibilidade contínua aos dados, mesmo quando uma zona de disponibilidade não está disponível. Um sistema de arquivos Multi-AZ foi desenvolvido para workloads de produção essenciais aos negócios que exigem alta disponibilidade para dados de arquivos ONTAP compartilhados e precisam de storage com replicação incorporada entre zonas de disponibilidade.
+
*Geração do sistema de arquivos*: Selecione uma das seguintes opções:

+
**** *Segunda geração*: Esta configuração de par único de HA é recomendada para cargas de trabalho que exigem até 6 GB/s de taxa de transferência ou 200.000 IOPS. Em um sistema de arquivos Multi-AZ e de segunda geração, a capacidade pode aumentar ou diminuir para atender às demandas da carga de trabalho.
**** *Primeira geração*: Esta configuração é ideal para cargas de trabalho que exigem até 4 GB/s ou 160.000 IOPS. Os sistemas de arquivos de primeira geração podem apenas aumentar a capacidade.




.. *Tags*: Opcionalmente, você pode adicionar até 50 tags.


. Em Detalhes do sistema de arquivos, forneça o seguinte:
+
.. *Capacidade de armazenamento SSD*: Introduza a capacidade de armazenamento e selecione a unidade de capacidade de armazenamento.
+
*** Para implantações de primeira geração, não é possível diminuir a capacidade após a criação do sistema de arquivos.
*** Para implantações de segunda geração, você pode ajustar a capacidade.


.. *Capacidade de transferência por par de HA*: Selecione a capacidade de transferência por número de pares de HA. Os sistemas de arquivos de primeira geração suportam apenas um par de HA.
.. *IOPS provisionados*: Selecione uma das seguintes opções:
+
*** *Automático*: Para automático, para cada GiB criado, 3 IOPS são adicionados.
*** *Provisionado pelo usuário*: para provisionado pelo usuário, insira o valor de IOPS.


.. *Credenciais ONTAP*: Opcional. Introduza o nome de utilizador e a palavra-passe do ONTAP. A senha pode ser definida agora ou mais tarde.
+
Se o usuário que você fornecer não for o usuário fsxadmin, e mais tarde você precisar redefinir a senha do fsxadmin, você poderá fazer isso no console da AWS.

.. * Credenciais de armazenamento de VM*: Opcional. Introduza o seu nome de utilizador. A palavra-passe pode ser específica para este sistema de ficheiros ou pode utilizar a mesma palavra-passe introduzida para as credenciais ONTAP. A senha pode ser definida agora ou mais tarde.
.. *Configuração SMB/CIFS*: Opcional. Se você planeja usar o protocolo SMB/CIFS para acessar volumes, configure o ative Directory para a VM de storage durante a criação do sistema de arquivos. Forneça os detalhes a seguir para a VM de storage criada para esse sistema de arquivos.
+
... *Domínio do ative Directory para ingressar*: Insira o nome de domínio totalmente qualificado (FQDN) para o ative Directory.
... *Endereços IP DNS*: Insira até três endereços IP DNS separados por vírgulas.
... *Nome NetBIOS do servidor SMB*: Insira o nome NetBIOS do servidor SMB do objeto computador do ative Directory a ser criado para sua VM de armazenamento. Este é o nome desta VM de armazenamento no ative Directory.
... *Nome de utilizador*: Introduza o nome de utilizador da conta de serviço no ative Directory existente.
+
Não inclua um prefixo ou sufixo de domínio. Para `EXAMPLE\ADMIN`, use `ADMIN`.

... *Senha*: Insira a senha da conta de serviço.
... * Unidade de organização*: Opcionalmente, insira o nome da Unidade organizacional onde você pretende criar a conta de computador para o FSX for ONTAP. A UO é o nome de caminho distinto da unidade organizacional à qual você deseja ingressar no sistema de arquivos.
... *Grupo de administradores delegados*: Opcionalmente, insira o nome do grupo no ative Directory que pode administrar seu sistema de arquivos.
+
Se você estiver usando o AWS Managed Microsoft AD, você deve especificar um grupo como Administradores delegados do FSX da AWS, Administradores delegados da AWS ou um grupo personalizado com permissões delegadas na UO.

+
Se você estiver se juntando a um AD autogerenciado, use o nome do grupo em seu AD. O grupo padrão é `Domain Admins`.





. Em rede e segurança, forneça o seguinte:
+
.. *Grupo de segurança*: Crie ou use um grupo de segurança existente.
+
Para um novo grupo de segurança, consulte <<Detalhes do grupo de segurança,detalhes do grupo de segurança>>para obter uma descrição dos protocolos, portas e funções do grupo de segurança.

.. *Zonas de disponibilidade*: Selecione zonas de disponibilidade e sub-redes.
+
*** Para o nó de configuração de cluster 1: Selecione uma zona de disponibilidade e uma sub-rede.
*** Para o nó de configuração de cluster 2: Selecione uma zona de disponibilidade e uma sub-rede.


.. *Tabelas de rota VPC*: Selecione a tabela de rota VPC para habilitar o acesso do cliente aos volumes.
.. *Intervalo de endereços IP do endpoint*: Selecione *intervalo de endereços IP flutuante fora da VPC* ou *Introduza um intervalo de endereços IP* e introduza um intervalo de endereços IP.
.. *Criptografia*: Selecione o nome da chave de criptografia no menu suspenso.


. Em Backup e manutenção, forneça o seguinte:
+
.. *FSX para backup ONTAP*: Backups automáticos diários são ativados por padrão. Desative, se desejado.
+
... *Período de retenção de backup automático*: Insira o número de dias para reter backups automáticos.
... *Janela de backup automático diário*: Selecione *sem preferência* (uma hora de início de backup diário está selecionada para você) ou *Selecione hora de início para backups diários* e especifique uma hora de início.


.. *Janela de manutenção semanal*: Selecione *Nenhuma preferência* (uma hora de início semanal da janela de manutenção está selecionada para você) ou *Selecione hora de início para a janela de manutenção semanal de 30 minutos* e especifique uma hora de início.


. Salve ou crie o sistema de arquivos.


Se você criou o sistema de arquivos, agora você pode visualizar o sistema de arquivos FSX for ONTAP na página *Inventário*.

--
====


== Detalhes do grupo de segurança

A tabela a seguir fornece detalhes do grupo de segurança, incluindo protocolos, portas e funções.

[]
====
[cols="2,2,4a"]
|===
| Protocolo | Porta | Função 


| SSH | 22  a| 
Acesso SSH ao endereço IP do LIF de gerenciamento de cluster ou um LIF de gerenciamento de nó



| TCP | 80  a| 
Acesso à página da Web ao endereço IP do LIF de gerenciamento de cluster



| TCP/UDP | 111  a| 
Chamada de procedimento remoto para NFS



| TCP/UDP | 135  a| 
Chamada de procedimento remoto para CIFS



| UDP | 137  a| 
Resolução de nomes NetBIOS para CIFS



| TCP/UDP | 139  a| 
Sessão de serviço NetBIOS para CIFS



| TCP | 443  a| 
Acesso à API REST do ONTAP ao endereço IP do LIF de gerenciamento de clusters ou de um LIF de gerenciamento de SVM



| TCP | 445  a| 
Microsoft SMB/CIFS sobre TCP com enquadramento NetBIOS



| TCP/UDP | 635  a| 
Montagem em NFS



| TCP | 749  a| 
Kerberos



| TCP/UDP | 2049  a| 
Daemon do servidor NFS



| TCP | 3260  a| 
Acesso iSCSI através do iSCSI data LIF



| TCP/UDP | 4045  a| 
Daemon de bloqueio NFS



| TCP/UDP | 4046  a| 
Monitor de status da rede para NFS



| UDP | 4049  a| 
Protocolo de cota NFS



| TCP | 10000  a| 
Protocolo de gerenciamento de dados de rede (NDMP) e comunicação NetApp SnapMirror entre clusters



| TCP | 11104  a| 
Gestão da comunicação NetApp SnapMirror entre clusters



| TCP | 11105  a| 
Transferência de dados SnapMirror usando LIFs entre clusters



| TCP/UDP | 161-162  a| 
Protocolo de gerenciamento de rede simples (SNMP)



| Todo o ICMP | Tudo  a| 
Fazer ping na instância

|===
====
.O que vem a seguir
Com um sistema de arquivos em seu inventário de armazenamento, você pode link:create-volume.html["criar volumes"]gerenciar seu sistema de arquivos FSX for ONTAP e configurar link:data-protection-overview.html["proteção de dados"]seus recursos.
