---
sidebar: sidebar 
permalink: create-volume.html 
keywords: create volume, FSx for ONTAP volume 
summary: Depois de configurar seu sistema de arquivos FSX for ONTAP, crie o FSX for ONTAP volumes na fábrica de carga de trabalho do BlueXP . 
---
= Crie um volume FSX for ONTAP na fábrica de cargas de trabalho do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Depois de configurar seu sistema de arquivos FSX for ONTAP, crie o FSX for ONTAP volumes na fábrica de carga de trabalho do BlueXP .

.Sobre esta tarefa
O FSX para ONTAP volumes são recursos virtuais usados para agrupar dados, determinar como os dados são armazenados e determinar o tipo de acesso aos seus dados. Os volumes não consomem a capacidade de storage do sistema de arquivos. Os dados armazenados em um volume consomem principalmente o armazenamento SSD. Dependendo da política de disposição em camadas do volume, os dados também podem consumir o storage do pool de capacidade. Você define o tamanho de um volume ao criá-lo e pode alterar seu tamanho mais tarde.

Os seguintes protocolos podem ser usados para seus volumes:

* CIFS: Protocolo de armazenamento de arquivos para sistemas operacionais Windows
* NFS: Protocolo de armazenamento de arquivos para sistemas operacionais Unix
* ISCSI: Protocolo de armazenamento de bloco


.Antes de começar
Reveja os seguintes pré-requisitos antes de criar um volume:

* Você deve ter um sistema de arquivos FSX for ONTAP na fábrica de carga de trabalho.
* Você precisa ter uma VM de storage.
* Para acesso ao protocolo, execute o seguinte:
+
** Para configurar o acesso ao volume, é link:manage-links.html["associe um link"]necessário . Se você não tiver um link existente, link:create-link.html["crie um link"]. Para associar um link no sistema de arquivos, selecione *associar link* sob *nome da conta*. Após os associados da ligação, volte a esta operação.
** Tem de configurar o acesso para o protocolo selecionado, seja CIFS, NFS ou iSCSI.






== Crie um volume

Você pode criar um volume usando as seguintes ferramentas disponíveis na Codebox: API REST, CloudFormation e Terraform. link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html#how-to-use-codebox["Saiba como usar o Codebox para automação"^].


NOTE: Ao usar o Terraform do Codebox, o código que você copia ou baixa oculta `fsxadmin` e `vsadmin` senhas. Você precisará digitar novamente as senhas quando executar o código.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos no qual você deseja criar um volume e selecione *criar volume*.
. Na página criar volume em Detalhes gerais, forneça os seguintes detalhes:
+
.. *Nome do volume*: Insira um nome para o volume.
.. *Storage VM name*: Opcionalmente, insira um nome de VM de armazenamento.
.. *Estilo de volume*: Selecione o volume *FlexVol* ou *FlexGroup*.
+
O estilo FlexVol volume é selecionado por padrão.

+
O tamanho do volume FlexGroup depende do número de componentes. 100 GiB é exigido por constituinte.

.. *Tamanho do volume*: Introduza o tamanho do volume e a unidade.
+
Opcionalmente, ative o volume com crescimento automático. Esta opção está disponível quando você seleciona *Acesso a arquivos* como o tipo de acesso de volume.

.. *Tags*: Opcionalmente, você pode adicionar até 50 tags.


. Em Access (somente para sistemas de arquivos com links associados), forneça os seguintes detalhes:
+
.. *Tipo de acesso*: Selecione *Acesso a arquivos* ou *Acesso a blocos*. Os campos adicionais para configurar o acesso ao volume diferem dependendo da sua seleção.
+
*** *Acesso a arquivos*: Permite que vários usuários e dispositivos autorizados acessem o volume usando protocolos SMB/CIFS, NFS ou dual (SMB/NFS).
+
Preencha os campos a seguir para configurar o acesso de arquivos ao volume.

+
.... *Política de exportação NFS*: Forneça os seguintes detalhes para fornecer acesso NFS:
+
..... *Controle de acesso*: Selecione uma política de exportação personalizada*, *Política de exportação existente* ou *nenhum acesso ao volume* no menu suspenso.
..... *Nome da política de exportação*:
+
Se você selecionou uma política de exportação personalizada, selecione um nome de política existente no menu suspenso.

+
Se tiver selecionado uma política de exportação existente, introduza um novo nome de política.

..... *Adicionar regra de política de exportação*: Opcionalmente, para uma política de exportação personalizada, você pode adicionar regras de política de exportação à política.


.... *Compartilhamento CIFS*: Forneça o seguinte:
+
..... *Nome*: Insira o nome do compartilhamento CIFS para fornecer acesso SMB.
..... *Permissões*: Selecione Controle completo, leitura/gravação, leitura ou sem acesso e insira os usuários ou grupos separados por ponto e vírgula ( ; ). Usuários ou grupos são sensíveis a maiúsculas e minúsculas e o domínio do usuário deve ser incluído usando o formato "domínio/nome de usuário".




*** *Acesso por bloco*: Permite aos hosts que executam aplicativos empresariais críticos acesso ao volume usando o protocolo iSCSI. O acesso a bloco só está disponível quando a implantação com escalabilidade horizontal do sistema de arquivos tiver seis pares de HA ou menos.
+
Preencha os campos a seguir para configurar o acesso de bloco ao volume.

+
.... *Configuração iSCSI*: Forneça os seguintes detalhes para configurar iSCSI para bloquear o acesso ao volume.
+
..... Selecione *criar um novo grupo de iniciadores* ou *mapear um grupo de iniciadores existente*.
..... Selecione o *sistema operativo anfitrião* no menu pendente.
..... Insira um *Nome do grupo do iniciador* para um novo grupo de iniciadores.
..... Em iniciadores de host, adicione um ou mais iniciadores de host de nome qualificado iSCSI (IQN).








. Sob a eficiência e a proteção, forneça os seguintes detalhes:
+
.. *Eficiência de armazenamento*: Desativar ou ativar a eficiência de armazenamento.
+
A eficiência de storage é obtida com a utilização de recursos de deduplicação e compactação do ONTAP. A deduplicação elimina blocos de dados duplicados. A compactação de dados compacta os blocos de dados para reduzir a quantidade de storage físico necessária.

.. *Arquivos immutáveis*: Esse recurso, também conhecido como SnapLock, está desativado por padrão. A ativação de arquivos imutáveis impede que os dados sejam excluídos ou substituídos por um período de tempo especificado. Ativar esta funcionalidade só é possível durante a criação de volume. Depois que o recurso estiver ativado, ele não poderá ser desativado. Este é um recurso premium para o FSX for ONTAP que carrega um custo adicional. Para obter mais informações, consulte a link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/how-snaplock-works.html["Como o SnapLock funciona"^]documentação do Amazon FSX for NetApp ONTAP.
+
A ativação do recurso arquivos imutáveis vincula permanentemente os arquivos neste volume para um estado WORM imutável (write-once-read-many).

+
Modos de retenção:: Você pode selecionar entre dois modos de retenção - _Enterprise_ ou _Compliance_.
+
--
*** No modo _Enterprise_, um administrador de arquivos imutáveis, ou SnapLock, pode excluir um arquivo durante seu período de retenção.
*** No modo _Compliance_, um arquivo WORM não pode ser excluído antes que seu período de retenção expire. Da mesma forma, o volume imutável não pode ser excluído até que os períodos de retenção de todos os arquivos dentro do volume expirem.


--
Período de retenção:: O período de retenção tem duas configurações - _política de retenção_ e _períodos de retenção_. A política de retenção _define quanto tempo reter arquivos em um estado WORM imutável. Você pode especificar sua própria política de retenção ou usar a política de retenção padrão (não especificada), que é de 30 anos. Os _períodos de retenção mínimo e máximo_ definem o intervalo de tempo permitido para bloquear arquivos.
+
--
NOTA:: Mesmo após o período de retenção expirar, você não pode modificar um arquivo WORM. Só é possível excluí-lo ou definir um novo período de retenção para ativar a proteção WORM novamente.


--
AUTOCOMMIT:: Você terá a opção de ativar o recurso de confirmação automática. O recurso de confirmação automática vincula um arquivo ao estado WORM em um volume SnapLock se o arquivo não for alterado durante o período de confirmação automática. O recurso de confirmação automática está desativado por padrão. Os arquivos que você deseja confirmar automaticamente devem residir em um volume SnapLock.
Modo de adição de volume:: Não é possível modificar dados existentes em um arquivo protegido WORM. No entanto, os arquivos imutáveis permitem manter a proteção de dados existentes usando arquivos anexados WORM. Por exemplo, você pode gerar arquivos de log ou preservar dados de streaming de áudio ou vídeo enquanto grava dados para eles de forma incremental. link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/worm-state.html#worm-state-append["Saiba mais sobre o modo de adição de volume"^] Na documentação do Amazon FSX for NetApp ONTAP.
+
--
.Etapas para arquivos imutáveis
... Selecione para ativar *ficheiros immutáveis alimentados pelo SnapLock*.
... Selecione a caixa para concordar e prosseguir.
... Selecione *Ativar*.
... *Modo de retenção*: Selecione o modo *Enterprise* ou *Compliance*.
... *Período de retenção*:
+
**** Selecione a política de retenção:
+
***** *Não especificado*: Define a política de retenção para 30 anos.
***** *Especificar período*: Insira o número de segundos, minutos, horas, dias, meses ou anos para definir sua própria política de retenção.


**** Selecione os períodos de retenção mínimo e máximo:
+
***** *Mínimo*: Insira o número de segundos, minutos, horas, dias, meses ou anos para definir o período mínimo de retenção.
***** *Máximo*: Insira o número de segundos, minutos, horas, dias, meses ou anos para definir o período máximo de retenção.




... *AUTOCOMMIT*: Desativar ou ativar o autocommit. Se você ativar a confirmação automática, defina o período de confirmação automática.
... *Modo de adição de volume*: Desativar ou ativar. Permite adicionar novo conteúdo a arquivos WORM.


--


.. *Política de snapshot*: Selecione a política de snapshot para especificar a frequência e a retenção de snapshots.
+
A seguir estão as políticas padrão da AWS. Para políticas de snapshot personalizadas, você deve associar um link.

+
`default`:: Essa política cria automaticamente snapshots na programação a seguir, com as cópias snapshot mais antigas excluídas para abrir espaço para cópias mais recentes:
+
--
*** Um máximo de seis snapshots por hora feitos cinco minutos depois da hora.
*** Um máximo de dois instantâneos diários tirados de segunda a sábado, 10 minutos após a meia-noite.
*** Um máximo de dois instantâneos semanais tirados todos os domingos, 15 minutos após a meia-noite.
+

NOTE: Os tempos de instantâneos baseiam-se no fuso horário do sistema de arquivos, que por padrão é Coordinated Universal Time (UTC). Para obter informações sobre como alterar o fuso horário, consulte a link:https://library.netapp.com/ecmdocs/ECMP1155684/html/GUID-E26E4C94-DF74-4E31-A6E8-1D2D2287A9A1.html["Apresentar e definir o fuso horário do sistema"^]documentação de suporte da NetApp.



--
`default-1weekly`:: Esta política funciona da mesma forma que a `default` política, exceto que só retém um instantâneo da programação semanal.
`none`:: Esta política não tira instantâneos. Você pode atribuir essa diretiva a volumes para impedir que snapshots automáticos sejam feitos.


.. *Política de disposição em categorias*: Selecione a política de disposição em categorias para os dados armazenados no volume.
+
Auto é a política de disposição em camadas padrão ao criar um volume usando a interface do usuário. Para obter mais informações sobre políticas de disposição em camadas de volume, consulte a link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidade de armazenamento de volume"^]documentação do AWS FSX for NetApp ONTAP.



. Em Configuração avançada, forneça o seguinte:
+
.. *Caminho de junção*: Insira o local no namespace da VM de armazenamento onde o volume é montado. O caminho de junção padrão é `/<volume-name>`.
.. *Lista de agregados*: Apenas para volumes FlexGroup. Adicionar ou remover agregados. O número mínimo de agregados é um.
.. *Número de componentes*: Apenas para volumes FlexGroup. Introduza o número de componentes por agregado. 100 GiB é exigido por constituinte.


. Selecione *criar*.


.Resultado
A criação de volume é iniciada. Uma vez criado, o novo volume aparecerá na guia volumes.
