---
sidebar: sidebar 
permalink: create-snapshot-policy.html 
keywords: create 
summary: Criar uma política de snapshot personalizada para uma VM de storage na fábrica de workloads do BlueXP . 
---
= Criar uma política de snapshot para VMs de storage na fábrica de workloads do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Criar uma política de snapshot personalizada para VMs de storage na fábrica de workloads do BlueXP . Uma política de snapshot define como o sistema cria snapshots para uma VM de storage. Você pode criar uma política de snapshot para uma VM de armazenamento em um sistema de arquivos FSX for ONTAP. Você também pode compartilhar a política em várias VMs de storage.

.Sobre esta tarefa
Você pode criar uma política de snapshot personalizada que difere das três políticas de snapshot internas do FSX for ONTAP:

* `default`
* `default-1weekly`
* `none`


Por padrão, cada volume está associado à política de snapshot do sistema de arquivos `default`. Recomendamos o uso desta política para a maioria das cargas de trabalho.

A personalização de uma política permite especificar quando criar snapshots, quantas cópias devem ser mantidas e como nomeá-las.

.Antes de começar
* Depois que uma política de snapshot é criada, sua associação com as VM de armazenamento não pode ser modificada, mas você sempre pode adicionar ou remover a política de volumes.
* Considere o seguinte sobre a capacidade de snapshot antes de usar snapshots:
+
** Para a maioria dos conjuntos de dados, uma capacidade adicional de 20% é suficiente para manter snapshots por até quatro semanas. À medida que os dados envelhecem, o uso delas para restaurações torna-se menos provável.
** A substituição de todos os dados em um snapshot consome capacidade de volume significativa, o que depende do provisionamento da capacidade do volume.


* Para criar uma política de instantâneos personalizada, tem link:manage-links.html["associe um link"]de . Se você não tiver um link existente, link:create-link.html["crie um link"]. Para associar um link no sistema de arquivos, selecione *associar link* sob *nome da conta*. Assim que o link se associar, volte a esta operação.


.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em *armazenamento*, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos com o volume e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Storage VMs*.
. Na guia *Storage VMs*, selecione o menu de três pontos para o volume a proteger com snapshots programados, depois *ações avançadas* e, em seguida, *Gerenciar políticas de snapshot*.
. Na página de gerenciamento de políticas de instantâneos, selecione *criar política de instantâneos*.
. No campo *Nome da política de instantâneo*, insira um nome para a política de instantâneo.
. Opcionalmente, insira uma descrição para a política de snapshot.
. Em *Policy schedule e copies*, selecione quando criar snapshots. Por exemplo, a cada minuto ou hora.
+
Pode selecionar mais de uma frequência.

. Em *número de cópias*, introduza o número de cópias a reter.
+
O número máximo de cópias é 1.023.

. Opcional: Em *convenção de nomenclatura*, insira um *prefixo* para a política.
. *Etiqueta de retenção* é preenchida automaticamente.
+
Este rótulo refere-se ao SnapMirror, ou rótulo de replicação que é usado para selecionar somente snapshots especificados para replicação da origem para o sistema de arquivos de destino.

. Opcional: Ative *instantâneos immutáveis* para qualquer horário que você precisar, defina o *período de retenção* para cada horário e aceite a instrução para continuar.
+
A ativação de instantâneos imutáveis bloqueia todos os instantâneos nesta política de instantâneos para impedir que os instantâneos sejam excluídos durante o período de retenção.

. *Compartilhar entre VMs de armazenamento*: Habilitado por padrão. Quando ativada, a política de snapshot é compartilhada em todas as VMs de armazenamento no sistema de arquivos. Desative para criar uma política de snapshot para uma única VM de armazenamento.
. Selecione *criar*.


.Resultado
A política de instantâneos é criada.
