---
sidebar: sidebar 
permalink: delete-replication.html 
keywords: delete replication 
summary: Exclua um relacionamento de replicação no NetApp Workload Factory conforme necessário. 
---
= Excluir um relacionamento de replicação no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Excluir um relacionamento de replicação no NetApp Workload Factory.  Quando você exclui um relacionamento de replicação, ele remove o relacionamento de replicação entre os volumes de origem e de destino.  Após a exclusão do relacionamento de replicação, ambos os volumes continuam a existir independentemente com os dados atuais que eles contêm.

Quando você exclui uma relação de replicação, o FSX for ONTAP também exclui os snapshots de replicação comuns do volume de origem e destino.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos a ser atualizado e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *relacionamentos de replicação*.
. Na guia Relacionamentos de replicação, selecione o menu de ações do relacionamento de replicação a ser excluído.
. Selecione *Eliminar*.
. Na caixa de diálogo Excluir relacionamento, selecione *Excluir*.

