---
sidebar: sidebar 
permalink: delete-file-system.html 
keywords: file system, delete file system, file system deletion 
summary: Para excluir um sistema de arquivos no workload do BlueXP  de fábrica, primeiro exclua volumes, máquinas virtuais de storage ou relações de replicação associadas ao sistema de arquivos. 
---
= Exclua um sistema de arquivos na fábrica de carga de trabalho do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Para excluir um sistema de arquivos no workload do BlueXP  de fábrica, primeiro exclua volumes, máquinas virtuais de storage ou relações de replicação associadas ao sistema de arquivos.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos FSX for ONTAP que você deseja excluir.
. Selecione *Gerenciar*.
. Na guia *Visão geral*, selecione o menu de três pontos.
. Selecione *Eliminar*.
. Na caixa de diálogo Excluir FSX for ONTAP sistema de arquivos, digite o nome do sistema de arquivos FSX for ONTAP para excluir.
. Selecione *Eliminar*.

