---
sidebar: sidebar 
permalink: delete-svm.html 
keywords: delete storage vm, delete svm, remove svm 
summary: 'Exclua uma VM de armazenamento (SVM) que você não precisa mais de uma configuração do sistema de arquivos do FSX for ONTAP.' 
---
= Exclua uma VM de storage na fábrica de workloads do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Exclua uma VM de armazenamento (SVM) que você não precisa mais de uma configuração do sistema de arquivos do FSX for ONTAP.

.Antes de começar
Reveja o seguinte antes de eliminar uma VM de armazenamento:

* Certifique-se de que nenhuma aplicação acesse os dados no SVM.
* Exclua todos os volumes que não sejam raiz anexados ao SVM.


.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos a ser atualizado e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Storage VMs*.
. Na guia Storage VMs (VMs de armazenamento), selecione o menu de três pontos da VM de armazenamento para a qual configurar o ative Directory.
. Selecione *Excluir VM de armazenamento*.
. Na caixa de diálogo Excluir VM de armazenamento, digite "excluir" para excluir a VM de armazenamento.
. Selecione *Eliminar*.

