---
sidebar: sidebar 
permalink: delete-replication.html 
keywords: delete replication 
summary: Exclua uma relação de replicação na fábrica de workloads do BlueXP , conforme necessário. 
---
= Excluir uma relação de replicação na fábrica de carga de trabalho do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Excluir uma relação de replicação na fábrica de carga de trabalho do BlueXP . Quando você exclui uma relação de replicação, ela remove a relação de replicação entre o volume de origem e destino. Após a exclusão da relação de replicação, ambos os volumes continuam a existir independentemente com os dados atuais que contêm.

Quando você exclui uma relação de replicação, o FSX for ONTAP também exclui os snapshots de replicação comuns do volume de origem e destino.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos a ser atualizado e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *relacionamentos de replicação*.
. Na guia relacionamentos de replicação, selecione o menu de três pontos da relação de replicação a ser excluída.
. Selecione *Eliminar*.
. Na caixa de diálogo Excluir relacionamento, selecione *Excluir*.

