---
sidebar: sidebar 
permalink: delete-volume.html 
keywords: delete volume, volume deletion 
summary: Você pode excluir um volume em seu sistema de arquivos FSX for ONTAP a qualquer momento. Esta operação é irreversível. 
---
= Exclua um volume na fábrica da carga de trabalho do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Você pode excluir um volume em seu sistema de arquivos FSX for ONTAP a qualquer momento. Esta operação é irreversível.

.Antes de começar
Considere o seguinte antes de excluir um volume:

* Relacionamentos de replicação: É necessário link:delete-replication.html["eliminar todas as relações de replicação existentes"] para esse volume antes de excluir o volume para que não haja relacionamentos quebrados.
* Snapshots locais: Todos os snapshots associados a este sistema de arquivos FSX for ONTAP serão excluídos permanentemente.
* Backup do FSX para ONTAP: As cópias de backup do FSX for ONTAP permanecerão e você ainda poderá usá-las.
* Arquivos imutáveis: Os volumes que contêm arquivos imutáveis alimentados pelo SnapLock não podem ser excluídos até que o período de retenção expire.


.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos com o volume a ser excluído e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. No separador volumes, selecione o menu de três pontos do volume a eliminar.
. Selecione *ações básicas* e, em seguida, *Excluir volume*.
. Na caixa de diálogo Excluir volume, faça o seguinte:
+
.. Opcionalmente, selecione *fazer backup do volume* para fazer backup do volume antes da exclusão.
+
O backup permanecerá no sistema de arquivos até que você o exclua manualmente.

.. Selecione *continuar*.
.. Digite "delete" para excluir o volume.
.. Selecione *Eliminar*.



