---
sidebar: sidebar 
permalink: delete-svm.html 
keywords: delete storage vm, delete svm, remove svm 
summary: 'Exclua uma VM de armazenamento (SVM) que você não precisa mais de uma configuração do sistema de arquivos do FSX for ONTAP.' 
---
= Excluir uma VM de armazenamento no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Exclua uma VM de armazenamento (SVM) que você não precisa mais de uma configuração do sistema de arquivos do FSX for ONTAP.

.Antes de começar
Reveja o seguinte antes de eliminar uma VM de armazenamento:

* Certifique-se de que nenhuma aplicação acesse os dados no SVM.
* Exclua todos os volumes que não sejam raiz anexados ao SVM.


.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos a ser atualizado e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Storage VMs*.
. Na guia VMs de armazenamento, selecione o menu de ações da VM de armazenamento para a qual deseja configurar o Active Directory.
. Selecione *Excluir VM de armazenamento*.
. Na caixa de diálogo Excluir VM de armazenamento, digite "excluir" para excluir a VM de armazenamento.
. Selecione *Excluir* para confirmar.

