---
sidebar: sidebar 
permalink: edit-volume-autogrow.html 
keywords: volume autogrow, increase volume capacity, enable autogrow 
summary: Habilite o crescimento automático de volume para permitir que o Workload Factory gerencie a capacidade de volume para você.  Você pode desativá-lo a qualquer momento. 
---
= Habilitar crescimento automático de volume no Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Habilite o crescimento automático de volume para permitir que o Workload Factory gerencie a capacidade de volume para você.  Você pode desativá-lo a qualquer momento.

Opcionalmente, você pode aumentar manualmente a capacidade de volume de um volume a qualquer momento usando olink:adjust-volume-capacity.html["recurso de ajuste de capacidade de volume"] .


NOTE: O volume com crescimento automático não é suportado para volumes iSCSI.

.Antes de começar
Para habilitar o crescimento automático de volume, você deve associar um link. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda como associar um link existente ou criar e associar um novo link"]. Após os associados da ligação, volte a esta operação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos com o volume a ser atualizado e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. Na guia Volumes, selecione o menu de ações do volume que você deseja modificar.
. Selecione *Ações básicas* e depois *Definir aumento automático de volume*.
. Na caixa de diálogo Definir crescimento automático, ative o crescimento automático de volume para expandir automaticamente a capacidade do volume até que ele atinja o tamanho máximo. Este recurso permite o aumento do uso de dados, garantindo operações ininterruptas.
+
Especifique o tamanho máximo de crescimento do volume e a unidade. O tamanho máximo de crescimento não pode ser menor que o tamanho do volume atual.

. Selecione *aplicar*.

