---
sidebar: sidebar 
permalink: edit-volume-autogrow.html 
keywords: volume autogrow, increase volume capacity, enable autogrow 
summary: Ative o volume com crescimento automático para permitir que o Workload Factory gerencie a capacidade de volume para você. Você pode desativá-lo a qualquer momento. 
---
= Ativar volume com crescimento automático
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Ative o volume com crescimento automático para permitir que o Workload Factory gerencie a capacidade de volume para você. Você pode desativá-lo a qualquer momento.

Opcionalmente, você pode aumentar manualmente a capacidade de volume de um volume a qualquer momento usando o link:increase-volume-capacity.html["recurso de aumento de capacidade de volume"].


NOTE: O volume com crescimento automático não é suportado para volumes iSCSI.

.Antes de começar
Para ativar o volume com crescimento automático, é link:manage-links.html["associe um link"]necessário . Se você não tiver um link existente, link:create-link.html["crie um link"]. Para associar um link no sistema de arquivos, clique em *associar link* em *nome da conta*. Assim que o link se associar, volte a esta operação.

.Passos
. Inicie sessão no link:https://console.workloads.netapp.com/["Console de fábrica da carga de trabalho"^]
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia FSX for ONTAP, selecione o menu de três pontos do sistema de arquivos com o volume a ser atualizado e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. Na guia volumes, selecione o menu três pontos para o volume que deseja modificar.
. Selecione *ações básicas* e, em seguida, *Editar volume com crescimento automático*.
. Na caixa de diálogo Editar crescimento automático, ative o volume com crescimento automático.
. Clique em *aplicar*.

