---
sidebar: sidebar 
permalink: edit-volume-autogrow.html 
keywords: volume autogrow, increase volume capacity, enable autogrow 
summary: Habilite o crescimento automático de volume para permitir que a fábrica de carga de trabalho gerencie a capacidade de volume para você. Você pode desativá-lo a qualquer momento. 
---
= Habilitar crescimento automático de volume na fábrica de carga de trabalho
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Habilite o crescimento automático de volume para permitir que a fábrica de carga de trabalho gerencie a capacidade de volume para você. Você pode desativá-lo a qualquer momento.

Opcionalmente, você pode aumentar manualmente a capacidade de volume de um volume a qualquer momento usando o link:increase-volume-capacity.html["recurso de aumento de capacidade de volume"].


NOTE: O volume com crescimento automático não é suportado para volumes iSCSI.

.Antes de começar
Para ativar o volume com crescimento automático, é link:manage-links.html["associe um link"]necessário . Se você não tiver um link existente, link:create-link.html["crie um link"]. Para associar um link no sistema de arquivos, selecione *associar link* sob *nome da conta*. Após os associados da ligação, volte a esta operação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia FSX for ONTAP, selecione o menu de três pontos do sistema de arquivos com o volume a ser atualizado e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. No separador volumes, selecione o menu de três pontos para o volume que pretende modificar.
. Selecione *Ações básicas* e depois *Definir aumento automático de volume*.
. Na caixa de diálogo Definir crescimento automático, ative o crescimento automático de volume para expandir automaticamente a capacidade do volume até que ele atinja o tamanho máximo. Este recurso permite o aumento do uso de dados, garantindo operações ininterruptas.
+
Especifique o tamanho máximo de crescimento do volume e a unidade. O tamanho máximo de crescimento não pode ser menor que o tamanho do volume atual.

. Selecione *aplicar*.

