---
sidebar: sidebar 
permalink: increase-volume-capacity.html 
keywords: increase capacity, volume capacity 
summary: Aumente manualmente a capacidade de um volume no NetApp Workload Factory a qualquer momento. 
---
= Aumente a capacidade de volume no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aumente manualmente a capacidade de um volume a qualquer momento no NetApp Workload Factory.

Opcionalmente, você podelink:edit-volume-autogrow.html["ative o recurso de crescimento automático"] para deixar que o Workload Factory gerencie a capacidade de volume para você.

.Sobre esta tarefa
Para um iSCSI LUN, esta operação aumenta o tamanho do LUN do host. Depois que a capacidade aumentar, siga o procedimento fornecido pelo sistema operacional host para descobrir o novo tamanho do LUN e expandir o sistema de arquivos do LUN.

.Antes de começar
Para aumentar a capacidade de volume, você deve associar um link. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda como associar um link existente ou criar e associar um novo link"]. Após os associados da ligação, volte a esta operação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos com o volume a ser atualizado e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. Na guia Volumes, selecione o menu de ações do volume para aumentar a capacidade.
. Selecione *ações básicas* e, em seguida, *aumentar a capacidade do volume*.
. Na caixa de diálogo aumentar a capacidade do volume, forneça o seguinte:
+
.. Selecione um tamanho maior.
.. Substitua a unidade, se necessário.


. Selecione *Aumentar* para aplicar a alteração.

