---
sidebar: sidebar 
permalink: increase-volume-capacity.html 
keywords: increase capacity, volume capacity 
summary: Aumente manualmente a capacidade de volume de um volume na fábrica de workloads da BlueXP  a qualquer momento. 
---
= Aumente a capacidade do volume no workload da BlueXP  de fábrica
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Aumente manualmente a capacidade de volume de um volume a qualquer momento na fábrica de workloads da BlueXP .

Opcionalmente, você pode link:edit-volume-autogrow.html["ative o recurso de crescimento automático"]permitir que o workload gerencie de fábrica a capacidade do volume para você.

.Sobre esta tarefa
Para um iSCSI LUN, esta operação aumenta o tamanho do LUN do host. Depois que a capacidade aumentar, siga o procedimento fornecido pelo sistema operacional host para descobrir o novo tamanho do LUN e expandir o sistema de arquivos do LUN.

.Antes de começar
Para aumentar a capacidade de volume, você deve associar um link. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda como associar um link existente ou criar e associar um novo link"]. Após os associados da ligação, volte a esta operação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos com o volume a ser atualizado e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. No separador volumes, selecione o menu de três pontos do volume para aumentar a capacidade.
. Selecione *ações básicas* e, em seguida, *aumentar a capacidade do volume*.
. Na caixa de diálogo aumentar a capacidade do volume, forneça o seguinte:
+
.. Selecione um tamanho maior.
.. Substitua a unidade, se necessário.


. Selecione *aumentar*.

