---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: As limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportadas por esta versão do produto ou que não interoperam corretamente com ele. 
---
= Limitações conhecidas do Amazon FSX for NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
As limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportadas por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações com cuidado.



== Link necessário para operações ONTAP avançadas

Um link é necessário para concluir algumas operações, como replicação na interface de usuário de fábrica de carga de trabalho.



== Adição de limitações de pares de HA

* Esta operação poderá demorar cerca de 30 minutos a concluir.
* A adição de pares de HA limita as seguintes operações: Adicionar mais pares de HA, provisionar IOPS, aumentar a capacidade das SSD e atualizar a capacidade da taxa de transferência.




== Suporte a região de capacidade de taxa de transferência



=== Implantações com escalabilidade vertical

As configurações de escalabilidade vertical são compatíveis com até 2 GB/s em todas as regiões. As seguintes regiões suportam capacidade máxima de até 4 GB/s para implantações de escalabilidade vertical: Região Leste DOS EUA (Ohio), região Leste dos EUA (Norte da Virgínia), região Oeste dos EUA (Oregon) e Europa (Irlanda).



=== Implantações com escalabilidade horizontal

As seguintes regiões suportam capacidade máxima de até 3 GB/s e 6 GB/s para implantações de escalabilidade horizontal: Leste DOS EUA (Norte da Virgínia), Leste dos EUA (Ohio), Oeste dos EUA (Oregon), Europa (Irlanda) e Pacífico Asiático (Sydney).



== Gerenciamento de capacidade

* A funcionalidade de volume com crescimento automático não é atualmente suportada para o protocolo iSCSI.
* Quando o recurso de gerenciamento automático de capacidade está sendo executado, o aumento manual de capacidade não é permitido.
* Desativar o recurso de gerenciamento automático de capacidade só é possível com as mesmas permissões usadas para ativá-lo.




== VMs de storage

O número de VMs de armazenamento é limitado por SKU. A criação de VMs de armazenamento além da limitação não é suportada na fábrica de cargas de trabalho. 1

Consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["Gerenciando o FSX para máquinas virtuais de armazenamento ONTAP"^]na documentação da AWS o número máximo de SVMs por sistema de arquivos.



== Suporte ao protocolo iSCSI

* O protocolo iSCSI só está disponível para volumes FlexVol. 1
* Apenas um único LUN pode ser configurado por volume.




== Proteção de dados

* Os instantâneos não podem ser eliminados.
* Quando você replica um sistema de arquivos, todos os volumes no sistema de arquivos usam a mesma política de replicação.
* Para relacionamentos de replicação de retenção de longo prazo, apenas o último snapshot está disponível para restauração.
* Os seguintes recursos não são suportados com snapshots imutáveis:
+
** Grupos de consistência
** FabricPool
** Volumes FlexCache
** SMtape
** Sincronização ativa do SnapMirror
** Regras de política do SnapMirror usando o parâmetro -schedule
** SnapMirror síncrono
** Mobilidade de dados SVM (usada para migrar ou realocar um SVM de um cluster de origem para um cluster de destino)






== Calculadora de economia de armazenamento

A calculadora de economia de armazenamento não calcula as economias de custo para as seguintes configurações:

* FSX para Windows File Server: Tipo de armazenamento HDD
* Elastic Block Store (EBS): ST1, SC1 e tipos de volume padrão
* Elastic File System (EFS): Modo de taxa de transferência de estouro




== System Manager

O System Manager não oferece suporte a links para a conetividade do FSX for ONTAP.



== Suporte ao AWS Secrets Manager

O AWS Secrets Manager não é suportado ao usar um conetor.

Nota:

. Aplica-se ao Amazon FSX for NetApp ONTAP

