---
sidebar: sidebar 
permalink: known-limitations.html 
keywords: limitations, fsx, ontap 
summary: As limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportadas por esta versão do produto ou que não interoperam corretamente com ele. 
---
= Limitações conhecidas do Amazon FSX for NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
As limitações conhecidas identificam plataformas, dispositivos ou funções que não são suportadas por esta versão do produto ou que não interoperam corretamente com ele. Revise essas limitações com cuidado.



== Suporte regional

As seguintes regiões da AWS não são suportadas:

* Regiões da China
* Regiões GovCloud (EUA)
* Nuvem Secreta
* Nuvem Top Secret




== Adição de limitações de pares de HA

* Esta operação poderá demorar cerca de 30 minutos a concluir.
* A adição de pares de HA limita as seguintes operações: Adicionar mais pares de HA, provisionar IOPS, aumentar a capacidade das SSD e atualizar a capacidade da taxa de transferência.




== Suporte a região de capacidade de taxa de transferência



=== Implantações com escalabilidade vertical

As configurações de escalabilidade vertical são compatíveis com até 2 GB/s em todas as regiões. As seguintes regiões suportam capacidade máxima de até 4 GB/s para implantações de escalabilidade vertical: Região Leste DOS EUA (Ohio), região Leste dos EUA (Norte da Virgínia), região Oeste dos EUA (Oregon) e Europa (Irlanda).



=== Implantações com escalabilidade horizontal

As seguintes regiões oferecem suporte a até 6 GB/s de capacidade máxima de transferência para implantações de expansão: Leste dos EUA (Norte da Virgínia e Ohio), Oeste dos EUA (Norte da Califórnia e Oregon), Europa (Frankfurt, Irlanda e Estocolmo) e Ásia-Pacífico (Cingapura e Sydney).



== Gerenciamento de capacidade

* A funcionalidade de volume com crescimento automático não é atualmente suportada para o protocolo iSCSI.
* Quando o recurso de gerenciamento automático de capacidade está sendo executado, o aumento manual de capacidade não é permitido.
* Desativar o recurso de gerenciamento automático de capacidade só é possível com as mesmas permissões usadas para ativá-lo.
* Quando o gerenciamento automático de capacidade está habilitado, um link é necessário para garantir que os inodes de volume aumentem junto com a capacidade de armazenamento.




== VMs de storage

O número de VMs de armazenamento é limitado por SKU.  A criação de VMs de armazenamento além do limite não é suportada no Workload Factory.^1^

Consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/managing-svms.html#max-svms["Gerenciando o FSX para máquinas virtuais de armazenamento ONTAP"^]na documentação da AWS o número máximo de SVMs por sistema de arquivos.



== Suporte ao protocolo iSCSI

* O protocolo iSCSI só está disponível para volumes FlexVol. 1
* A redução do tamanho do volume não é suportada para volumes iSCSI.




== Proteção de dados

* Os instantâneos não podem ser eliminados.
* Quando você replica um sistema de arquivos, todos os volumes no sistema de arquivos usam a mesma política de replicação.
* Para relacionamentos de replicação de retenção de longo prazo, apenas o último snapshot está disponível para restauração.
* Os seguintes recursos não são suportados com snapshots imutáveis:
+
** Grupos de consistência
** FabricPool
** Volumes FlexCache
** SMtape
** Sincronização ativa do SnapMirror
** Regras de política do SnapMirror usando o parâmetro -schedule
** SnapMirror síncrono
** Mobilidade de dados SVM (usada para migrar ou realocar um SVM de um cluster de origem para um cluster de destino)






== Calculadora de economia de armazenamento

A calculadora de economia de armazenamento não calcula as economias de custo para as seguintes configurações:

* FSX para Windows File Server: Tipo de armazenamento HDD
* Elastic Block Store (EBS): ST1, SC1 e tipos de volume padrão
* Elastic File System (EFS): Modo de taxa de transferência de estouro




== Suporte ao AWS Secrets Manager

O AWS Secrets Manager não é compatível ao usar um agente do Console.



== Limitação de pontos de acesso do Amazon S3

O limite para o número de pontos de acesso S3 por máquina virtual de armazenamento é 4.000.

Nota:

. Aplica-se ao Amazon FSX for NetApp ONTAP

