---
sidebar: sidebar 
permalink: learn-fsx-ontap.html 
keywords: Amazon FSx for NetApp ONTAP, FSx, storage, aws 
summary: O Amazon FSx for NetApp ONTAP é um serviço totalmente gerenciado que permite aos clientes iniciar e executar sistemas de arquivos como backend de armazenamento para suas cargas de trabalho no Workload Factory. 
---
= Saiba mais sobre o Amazon FSx for NetApp ONTAP no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O Amazon FSx for NetApp ONTAP é um serviço de armazenamento de dados totalmente gerenciado e baseado em nuvem que fornece recursos avançados de gerenciamento de dados e desempenho altamente escalável.  O FSx for ONTAP permite que você crie e gerencie sistemas de arquivos como backend de armazenamento para todas as suas cargas de trabalho no NetApp Workload Factory.

O FSX para ONTAP oferece os mesmos recursos, performance e funcionalidades administrativas que os clientes da NetApp usam no local hoje, com a simplicidade, agilidade, segurança e escalabilidade de um serviço AWS nativo.

FSx para ONTAP é o componente _Armazenamento_ no Workload Factory.



== Caraterísticas

O FSX para ONTAP oferece os seguintes recursos:

* *Serviço totalmente gerenciado*: fornece um serviço totalmente gerenciado integrado ao console do Workload Factory.
* *Alta disponibilidade*: Fornece alta disponibilidade para cada sistema de arquivos FSX for ONTAP, suportando implantações de zonas de disponibilidade única e múltipla.
* *Instantâneos automatizados*: Protege os dados com snapshots automatizados e eficientes, que são cópias pontuais e quase instantâneas do sistema de arquivos ou volumes, com uso eficiente de espaço.
* *Replicação de volume*: Fornece recuperação de desastres com replicação entre regiões na Amazon Web Services.
* * Backups eficientes*: Adiciona uma camada extra de proteção com uma cópia dos dados em outra região para emergências.
* * Clonagem rápida*: Acelera o desenvolvimento de aplicativos com clonagem rápida.
* *Suporte multiprotocolo*: Suporta protocolos NFS (Network File System), SMB (Server Message Block) e iSCSI (Internet Small Computer Systems Interface).
* * Alta taxa de transferência*: Oferece alto desempenho de taxa de transferência para garantir baixas latências para cargas de trabalho executadas em sistemas de arquivos FSX for ONTAP.
* *Cache na memória e cache NVMe*: Inclui um cache exclusivo na memória e cache NVMe, que aumenta o desempenho de dados acessados com frequência.
* *Centenas de milhares de IOPS*: Fornece centenas de milhares de IOPS com discos SSD, garantindo que seu armazenamento e cargas de trabalho recebam resultados oportunos.
* *Provisionamento de thin*: Permite o provisionamento de capacidade com antecedência, economizando custos até que seja necessária mais capacidade.
* * Deduplicação e compactação de dados*: Remove dados duplicados e compacta dados para reduzir a quantidade de armazenamento físico necessário para os sistemas de arquivos FSX for ONTAP, resultando em economia de custos.
* *Disposição em camadas de dados*: Permite a redução de custos de storage movendo dados acessados com menos frequência da camada de storage SSD principal de alto desempenho para a camada de storage do pool de capacidade secundária.




== Recursos adicionais no Workload Factory

* * Calculadora de comparação de custos de armazenamento*: Compara os custos de armazenamento do Amazon Elastic Block Store (EBS), Elastic File System (EFS) e FSX para Windows File Server com o FSX for ONTAP. A partir da calculadora, você pode ver como as configurações de armazenamento do FSX for ONTAP oferecem economias potenciais e Planejar sua migração para o FSX for ONTAP.
* *Interface de usuário do Workload Factory*: Fornece opções de modo de implantação _Quick Create_ e _Advanced Create_. O Quick Create inclui a AWS, o NetApp e as práticas recomendadas padrão do setor para suas configurações de storage.
* *Codebox*: Fornece aos desenvolvedores um visualizador de código para operações do FSX for ONTAP, modelos de código para cópia e download e um catálogo de automação para reutilização de código.




== Ferramentas para usar o NetApp Workload Factory

Você pode usar o NetApp Workload Factory com as seguintes ferramentas:

* *Console do Workload Factory*: O console do Workload Factory fornece uma visão visual e holística de seus aplicativos e projetos.
* * NetApp Console*: O NetApp Console oferece uma experiência de interface híbrida para que você possa usar o Workload Factory junto com outros serviços de dados do NetApp .
* *Pergunte-me*: use o assistente de IA Ask me para fazer perguntas e saber mais sobre o Workload Factory sem sair do console do Workload Factory. Acesse Pergunte-me no menu de ajuda do Workload Factory.
* *CloudShell CLI*: O Workload Factory inclui um CloudShell CLI para gerenciar e operar ambientes AWS e NetApp em todas as contas a partir de um único CLI baseado em navegador. Acesse o CloudShell na barra superior do console do Workload Factory.
* *API REST*: Use as APIs REST do Workload Factory para implantar e gerenciar seu FSx para sistemas de arquivos ONTAP e outros recursos da AWS.
* *CloudFormation*: use o código do AWS CloudFormation para executar as ações definidas no console do Workload Factory para modelar, provisionar e gerenciar recursos da AWS e de terceiros da pilha do CloudFormation na sua conta da AWS.
* *Provedor do Terraform NetApp Workload Factory*: use o Terraform para criar e gerenciar fluxos de trabalho de infraestrutura gerados no console do Workload Factory.




== Custo

A AWS mantém sua conta FSx para ONTAP , não o Workload Factory. Consulte link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/what-is-fsx-ontap.html#pricing-for-fsx-ontap["Definição de preço do Amazon FSX for NetApp ONTAP"^] .



== Regiões

A fábrica de carga de trabalho é suportada em todas as regiões comerciais onde o FSx para ONTAP é suportado.link:https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/["Exibir regiões da Amazon compatíveis."^]

As seguintes regiões da AWS não são suportadas:

* Regiões da China
* Regiões GovCloud (EUA)
* Nuvem Secreta
* Nuvem Top Secret




== Obter ajuda

O Amazon FSX for NetApp ONTAP é uma solução exclusiva da AWS. Para dúvidas ou problemas de suporte técnico associados ao ONTAP sistema de arquivos, infraestrutura ou qualquer solução usando este serviço, use a Central de suporte no Console de Gerenciamento da AWS para abrir um caso de suporte com a AWS. Selecione o serviço "FSX for ONTAP" e a categoria apropriada. Forneça as informações restantes necessárias para criar seu caso de suporte da AWS.

Para perguntas gerais sobre o Workload Factory ou aplicativos e serviços do Workload Factory, consultelink:get-help.html["Obtenha ajuda para FSx para ONTAP para Workload Factory"] .
