---
sidebar: sidebar 
permalink: limit-transfer-rate.html 
keywords: limit max transfer rate, limit transfer rate 
summary: Limite a taxa máxima de transferência de uma relação de replicação na fábrica de carga de trabalho do BlueXP . 
---
= Limite a taxa máxima de transferência de uma relação de replicação
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Limite a taxa máxima de transferência de uma relação de replicação na fábrica de carga de trabalho do BlueXP . Uma taxa de transferência ilimitada pode afetar negativamente o desempenho de outros aplicativos e sua rede.

.Sobre esta tarefa
Limitar a taxa máxima de transferência é opcional, mas recomendado. Sem um limite, o desempenho da rede e do aplicativo pode declinar.

Como alternativa, recomendamos uma taxa de transferência ilimitada para os sistemas de arquivos FSX for ONTAP para cargas de trabalho críticas, por exemplo, aquelas que são usadas principalmente para recuperação de desastres.

.Antes de começar
Considere a quantidade de largura de banda a alocar para replicação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos a ser atualizado e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *relacionamentos de replicação*.
. Na guia relacionamentos de replicação, selecione o menu de três pontos da relação de replicação para limitar a taxa de transferência máxima para.
. Selecione *Editar taxa de transferência máxima*.
. Na caixa de diálogo Edit Max transfer rate (Editar taxa de transferência máxima), selecione *Limited* (limitado) e introduza o limite máximo de transferência em MB/s.
+
Em alternativa, selecione *Unlimited*.

. Selecione *aplicar*.

