---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Um link de fábrica de carga de trabalho cria uma relação de confiança e conetividade entre uma conta de fábrica de carga de trabalho e um ou mais sistemas de arquivos FSX for ONTAP. 
---
= Saiba mais sobre os links de fábrica da carga de trabalho do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Um link de fábrica da carga de trabalho do BlueXP  cria uma relação de confiança e conetividade entre uma conta de fábrica de carga de trabalho e um ou mais sistemas de arquivos do FSX for ONTAP. Isso permite que você monitore e gerencie certos recursos do sistema de arquivos diretamente das chamadas da API REST do ONTAP que não estão disponíveis através da API do Amazon FSX for ONTAP.

Você não precisa de um link para começar a trabalhar na fábrica de cargas de trabalho, mas em alguns casos você precisará criar um link para desbloquear todos os recursos de fábrica de cargas de trabalho e recursos de carga de trabalho.



== Como os links funcionam

Os links aproveitam o AWS Lambda. O Lambda executa código em resposta a eventos e gerencia automaticamente os recursos de computação exigidos por esse código. Os links que você cria fazem parte da sua conta do NetApp e são associados a uma conta da AWS.

Depois de criar um link, você pode associá-lo a um ou muitos sistemas de arquivos FSX for ONTAP. Cada sistema de arquivos pode ser associado apenas a um link na mesma conta do NetApp. Se você tiver várias contas do NetApp, um único sistema de arquivos pode ser associado a links adicionais em diferentes contas do NetApp.

Você cria links a partir das páginas do sistema de arquivos FSX for ONTAP na fábrica de carga de trabalho. link:create-link.html["Saiba como criar links"] para mais detalhes.

Você pode fazer links autênticos usando credenciais armazenadas no serviço de credenciais de fábrica de carga de trabalho ou com suas credenciais armazenadas no AWS Secrets Manager. A fábrica de carga de trabalho não suporta a alteração dos modos de autenticação.



== Custos

Cada transação que o Lambda executa incorre em uma cobrança. Como o Lambda atua como um proxy entre os dois sistemas, há uma cobrança quando o Lambda envia uma solicitação à API REST do ONTAP em um sistema de arquivos e quando envia a resposta de volta à fábrica de carga de trabalho.

link:https://aws.amazon.com/lambda/pricing/["Saiba mais sobre os custos relacionados ao uso do AWS Lambda"^]



== Quando um link é necessário

A fábrica da carga de trabalho requer um link para exibir algumas informações e executar algumas tarefas. Se você tentar executar uma operação que requer um link e você não associou um link ao sistema de arquivos FSX for ONTAP, você verá uma mensagem informando que a operação requer um link. Você pode adicionar um novo link ou associar o sistema de arquivos FSX for ONTAP a um link existente naquele momento para que você possa executar a operação.

Os recursos que exigem um link incluem:

* Exibindo a versão do ONTAP que está instalada em um sistema de arquivos FSX for ONTAP
* Gerenciamento de volumes iSCSI em um sistema de arquivos FSX for ONTAP
* Recurso de crescimento automático para volumes
* Criação e gerenciamento de políticas de snapshot
* Configuração da relação de replicação
* Replicação de volume entre o FSX para sistemas de arquivos ONTAP
* Configuração da relação de backup
* Backups de dados de volume para o storage de nuvem
* Clones de volume em um sistema de arquivos FSX for ONTAP
* Exibição de métricas adicionais diretamente do ONTAP (métricas padrão são coletadas pelo Amazon CloudWatch)
* Gerenciamento de políticas de exportação de NFS
* Gerenciamento de compartilhamentos CIFS

