---
sidebar: sidebar 
permalink: links-overview.html 
keywords: links, accounts, lambda 
summary: Um link do Workload Factory cria uma relação de confiança e conectividade entre uma conta do Workload Factory e um ou mais sistemas de arquivos FSx para ONTAP . 
---
= Saiba mais sobre os links do NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Um link do NetApp Workload Factory cria uma relação de confiança e conectividade entre uma conta do Workload Factory e um ou mais sistemas de arquivos FSx para ONTAP .  Isso permite que você monitore e gerencie determinados recursos do sistema de arquivos diretamente das chamadas da API REST do ONTAP que não estão disponíveis por meio da API do Amazon FSx para ONTAP .

Você não precisa de um link para começar a usar o Workload Factory, mas em alguns casos você precisará criar um link para desbloquear todos os recursos e funcionalidades de carga de trabalho do Workload Factory.



== Por que os links são benéficos

Os links são benéficos porque permitem que o Workload Factory execute operações que não estão disponíveis nativamente por meio da API do Amazon FSx para ONTAP .  Os links permitem recursos e automações ONTAP avançados, que aprimoram o gerenciamento do FSx para sistemas de arquivos ONTAP .

Aqui estão alguns benefícios de usar links:

* O link permite que o NetApp Console envie comandos ONTAP diretamente para o seu sistema de arquivos FSx for ONTAP , trazendo recursos ONTAP avançados além do que a AWS oferece nativamente.
* Os links utilizam o AWS Lambda para executar código em resposta a eventos. Essa abordagem sem servidor elimina a dependência de uma instância em execução na sua VPC.




== Como os links funcionam

Os links aproveitam o AWS Lambda. O Lambda executa código em resposta a eventos e gerencia automaticamente os recursos de computação exigidos por esse código. Os links que você cria fazem parte da sua conta do NetApp e são associados a uma conta da AWS.

Depois de criar um link, você pode associá-lo a um ou vários sistemas de arquivos FSx for ONTAP . Cada sistema de arquivos pode ser associado apenas a um link na mesma conta do NetApp. Se você tiver várias contas do NetApp, um único sistema de arquivos pode ser associado a links adicionais em diferentes contas do NetApp.

Você cria e associa links da carga de trabalho de armazenamento no Workload Factory.

Você pode autenticar links usando credenciais armazenadas no serviço de credenciais do Workload Factory ou com suas credenciais armazenadas no AWS Secrets Manager.  A fábrica de carga de trabalho não oferece suporte à alteração dos modos de autenticação.



== Custos

Cada transação realizada pelo Lambda gera uma cobrança.  Como o Lambda atua como um proxy entre os dois sistemas, há uma cobrança quando o Lambda envia uma solicitação à API REST do ONTAP em um sistema de arquivos e quando ele envia a resposta de volta ao Workload Factory.

link:https://aws.amazon.com/lambda/pricing/["Saiba mais sobre os custos relacionados ao uso do AWS Lambda"^]



== Quando um link é necessário

A fábrica de carga de trabalho requer um link para exibir algumas informações e executar algumas tarefas.  Se você tentar executar uma operação que requer um link e não tiver associado um link ao sistema de arquivos FSx for ONTAP , o Workload Factory notificará você de que a operação requer um link.

Os recursos que exigem um link incluem:

* Status bem arquitetado do FSx para configurações do sistema de arquivos ONTAP para manutenção proativa, confiabilidade e otimização de custo-desempenho
* Monitoramento e alerta de eventos do ONTAP EMS
* Proteção Autônoma contra Ransomware da NetApp (ARP/AI)
* Capacidade de observação holística aprimorada no FSx para sistemas de arquivos ONTAP
* Replicação, gerenciamento e monitoramento de dados de VM de volume e armazenamento
* Ações SMB/CIFS e provisionamento e gestão de políticas de exportação NFS
* Gerenciamento de volumes iSCSI em um sistema de arquivos FSX for ONTAP
* Criação e gerenciamento de políticas de snapshot para SLA de proteção personalizado
* Melhorias no gerenciamento de inodes para gerenciamento automático de capacidade
* Crescimento automático de volume para dimensionamento elástico
* Criação e gerenciamento de clones para clonagem instantânea de dados no local
* Exibindo métricas adicionais diretamente do ONTAP , como a versão do ONTAP


Aprenda a link:create-link.html["conectar um link a um sistema de arquivos FSx para ONTAP"].
