---
sidebar: sidebar 
permalink: manage-nfs-export-policy.html 
keywords: NFS, nfs, export policy, change export policy, update export policy, modify export policy 
summary: Gerenciar a política de exportação de NFS para um volume que usa tipos de protocolo NFSv3 ou NFSv4,1 na fábrica de workloads do BlueXP . 
---
= Gerenciar a política de exportação de NFS para um volume na fábrica de workloads do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Gerenciar a política de exportação de NFS para um volume que usa tipos de protocolo NFSv3 ou NFSv4,1 na fábrica de workloads do BlueXP .

.Sobre esta tarefa
O gerenciamento da política de exportação de um volume envolve a adição de regras de política de exportação que detalham as especificações do cliente, controle de acesso, acesso a super usuário e versão NFS. Você pode adicionar mais de uma política de exportação e priorizá-la.

.Antes de começar
Determine as especificações do cliente para as regras de política de exportação. Os valores válidos para a especificação do cliente são os seguintes:

* Endereços IP
* Endereços IP com máscaras de sub-rede
* Endereços IP com uma máscara de rede
* Um nome netgroup precedido pelo caractere ".at"
* Um nome de domínio precedido por um período "."
* Nomes de host


.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos com o volume a ser atualizado e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. Na guia volumes, selecione o menu de três pontos para o volume para o qual deseja alterar a política de exportação NFS.
. Selecione *ações avançadas* e, em seguida, *Editar política de exportação NFS*.
. Na página Editar política de exportação NFS, forneça o seguinte:
+
.. *Controle de acesso*: Selecione *Política de exportação personalizada* ou *Política de exportação existente*.
+
Em alternativa, pode selecionar *sem acesso ao volume*.

.. *Nome da política de exportação*: Opcionalmente, insira um nome para a política de exportação.
.. *Adicionar regra de política de exportação*: Forneça os seguintes detalhes e classifique as políticas começando com o número 1 como regra de prioridade:
+
... *Especificação do cliente*: Separe vários valores com vírgulas.
... *Controle de acesso*: Selecione *leitura/gravação*, *somente leitura* ou *sem acesso* no menu suspenso.
... *Super acesso ao usuário*: Selecione *Sim* ou *não*.
... *Versão NFS*: Selecione *All*, *NFSv3* ou *NFSv4*.




. Selecione *aplicar*.

