---
sidebar: sidebar 
permalink: manage-cache-volumes.html 
keywords: cache volumes, manage cache, FSx for ONTAP cache 
summary: Gerencie os volumes de cache para um sistema de arquivos FSx for ONTAP no NetApp Workload Factory quando necessário. 
---
= Gerencie volumes de cache do FSx para ONTAP com o NetApp Workload Factory.
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Utilize o console do NetApp Workload Factory para gerenciar volumes de cache para sistemas de arquivos FSx para ONTAP .  O armazenamento em cache, um método para guardar dados temporariamente, melhora o desempenho do acesso aos dados, reduzindo o tempo de recuperação.  Você pode editar o nome do cache, ajustar a capacidade, alterar a política de exportação, selecionar um método de cache, preencher previamente o cache ou excluir volumes de cache.

.Sobre esta tarefa
É possível gerenciar volumes de cache associados a relacionamentos de cache no console do NetApp Workload Factory .

.Antes de começar
* Você precisa associar um link para gerenciar volumes e relacionamentos de cache. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda como associar um link existente ou criar e associar um novo link"]. Após associar o link, retorne a esta operação.
* Você precisa ter um volume de cache existente para editar.




== Edite o nome do volume de cache.

Altere o nome de um volume de cache existente a qualquer momento.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione FSx para ONTAP.
. No FSx para ONTAP, selecione o menu de ações do sistema de arquivos com o volume de cache e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Relações de cache*.
. Selecione o menu de ações do volume de cache que deseja modificar e, em seguida, selecione *Editar nome do cache*.
. Na caixa de diálogo *Editar nome do cache*, insira o novo nome para o volume de cache e selecione *Aplicar*.




== Ajustar a capacidade de um volume de cache

Você pode ajustar a capacidade de um volume de cache existente a qualquer momento.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione FSx para ONTAP.
. No FSx para ONTAP, selecione o menu de ações do sistema de arquivos com o volume de cache e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Relações de cache*.
. Selecione o menu de ações para o volume de cache que deseja modificar e, em seguida, selecione *Ajustar capacidade do cache*.
. Na caixa de diálogo *Ajustar capacidade do cache*, insira a nova capacidade do volume do cache em porcentagem ou em unidade e selecione *Aplicar*.




== Editar a política de exportação do volume de cache

Alterar o caminho de montagem ou a política de exportação atribuída a um volume de cache existente.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione FSx para ONTAP.
. No FSx para ONTAP, selecione o menu de ações do sistema de arquivos com o volume de cache e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Relações de cache*.
. Selecione o menu de ações do volume de cache que deseja modificar e, em seguida, selecione *Editar política de exportação*.
. Na caixa de diálogo *Editar política de exportação*, altere o caminho de montagem ou selecione uma política de exportação diferente para atribuir ao volume de cache.
. Selecione *aplicar*.




== Alterar o método de cache para um volume de cache

Você pode alterar o funcionamento do cache de um volume de cache existente para write-around ou write-back.

Saiba mais sobrelink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/using-flexcache.html["modos de escrita"^] .

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione FSx para ONTAP.
. No FSx para ONTAP, selecione o menu de ações do sistema de arquivos com o volume de cache e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Relações de cache*.
. Selecione o menu de ações do volume de cache que deseja modificar e, em seguida, selecione *Alterar método de cache*.
. Na caixa de diálogo *Alterar método de cache*, selecione o novo método de cache e, em seguida, selecione *Aplicar*.




== Pré-popular um volume de cache

Preencha o volume de cache com dados do volume de origem antes de usá-lo para disponibilizar os dados em cache mais rapidamente.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione FSx para ONTAP.
. No FSx para ONTAP, selecione o menu de ações do sistema de arquivos com o volume de cache e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Relações de cache*.
. Selecione o menu de ações para o volume de cache que deseja modificar e, em seguida, selecione *Preencher cache*.
. Na caixa de diálogo *Preencher cache*, especifique o caminho para o conjunto de dados a ser usado para o preenchimento prévio e selecione *Aplicar*.




== Excluir um volume de cache

Ao excluir um volume de cache, você remove o relacionamento de cache associado a ele.  Os dados em cache não estão mais disponíveis.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione FSx para ONTAP.
. No FSx para ONTAP, selecione o menu de ações do sistema de arquivos com o volume de cache e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Relações de cache*.
. Selecione o menu de ações do volume de cache que deseja excluir e, em seguida, selecione *Excluir volume de cache*.
. Na caixa de diálogo *Excluir volume de cache*, confirme a exclusão e selecione *Excluir*.

