---
sidebar: sidebar 
permalink: manage-cifs-share.html 
keywords: cifs, smb, SMB/CIFS, cifs share, change, update, modify, delete, create 
summary: Gerenciar o compartilhamento SMB/CIFS de um volume no workload factory inclui criação, determinação de acesso de usuários e grupos e exclusão. 
---
= Gerenciar o compartilhamento SMB/CIFS para um volume na fábrica de carga de trabalho
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O gerenciamento do compartilhamento SMB/CIFS de um volume no workload factory inclui a criação do compartilhamento SMB/CIFS, a determinação dos usuários e grupos aos quais será concedido acesso e o nível de permissões a serem concedidos a eles, além da exclusão do compartilhamento SMB/CIFS.

.Antes de começar
Antes de começar, faça o seguinte:

* Para gerenciar compartilhamentos SMB/CIFS, você deve associar um link. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda como associar um link existente ou criar e associar um novo link"] .  Após o link associar, retorne a esta operação.
* Determine os usuários ou grupos para dar acesso e o nível de permissões para dar a eles.




== Crie um compartilhamento SMB/CIFS para um volume

Siga as etapas para criar um compartilhamento SMB/CIFS para um volume.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos com o volume a ser atualizado e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. No separador volumes, selecione o menu de três pontos do volume para o qual pretende alterar a partilha SMB.
. Selecione *Ações avançadas* e depois *Gerenciar compartilhamentos SMB/CIFS*.
. Na página Gerenciar compartilhamentos SMB/CIFS, selecione *Criar compartilhamento SMB/CIFS*.
. Na caixa de diálogo Criar compartilhamento SMB/CIFS, forneça o seguinte:
+
.. *Nome*: Digite o nome do compartilhamento SMB/CIFS.
.. *Caminho*: Defina o caminho usando o nome do volume padrão ou forneça um compartilhamento para um diretório interno.
+
As entradas de caminho válidas para o nome do volume, por exemplo "abacate", são as seguintes:

+
*** /abacate
*** /abacate/pasta
*** /abacate/pasta/subpasta
*** /abacate/nome-do-arquivo
+
As entradas de caminho válidas para o nome do compartilhamento, por exemplo "Servidor", são as seguintes:

*** \\Servidor
*** \\Servidor\Projetos
*** \\Servidor\Projetos\Recursos compartilhados


.. *Permissões*: Selecione Controle completo, leitura/gravação, leitura ou sem acesso e insira os usuários ou grupos separados por ponto e vírgula ( ; ). Usuários ou grupos são sensíveis a maiúsculas e minúsculas e o domínio do usuário deve ser incluído usando o formato "domínio/nome de usuário".


. Selecione *criar*.




== Alterar um compartilhamento SMB/CIFS para um volume

Siga as etapas para alterar as configurações de compartilhamento SMB/CIFS para um volume.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos com o volume a ser atualizado e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. No separador volumes, selecione o menu de três pontos do volume para o qual pretende alterar a partilha SMB.
. Selecione *Ações avançadas* e depois *Gerenciar compartilhamentos SMB/CIFS*.
. Na página Gerenciar compartilhamentos SMB/CIFS, selecione *Exibir e editar*.
. Altere as permissões de acesso SMB/CIFS ou os usuários ou grupos aos quais deseja conceder permissões.
+
Alterações podem fazer com que usuários ou grupos atuais percam o acesso ao compartilhamento SMB/CIFS.

. Selecione *Apply* para salvar as alterações.




== Excluir um compartilhamento SMB/CIFS para um volume

Siga as etapas para excluir um compartilhamento SMB/CIFS de um volume.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos com o volume a ser atualizado e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. No separador volumes, selecione o menu de três pontos do volume para o qual pretende alterar a partilha SMB.
. Selecione *Ações avançadas* e depois *Gerenciar compartilhamentos SMB/CIFS*.
. Na página Gerenciar compartilhamentos SMB/CIFS, selecione o menu de três pontos do compartilhamento SMB/CIFS e selecione *Excluir*.
+
Excluir o compartilhamento SMB/CIFS o torna indisponível e inacessível para qualquer usuário que queira montá-lo.

. Na caixa de diálogo Excluir compartilhamento SMB/CIFS, selecione *Excluir* para confirmar a exclusão.

