---
sidebar: sidebar 
permalink: manage-snapshot-policy.html 
keywords: manage snapshot policy, change snapshot policy, snapshot policies, snapshot schedule, update 
summary: Gerencie políticas de snapshot para volumes FSx for ONTAP no Workload Factory.  Uma política de snapshot define como o sistema cria snapshots para um volume. 
---
= Gerenciar políticas de snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Gerencie políticas de snapshot para volumes FSx for ONTAP no Workload Factory.  Uma política de snapshot define como o sistema cria snapshots para um volume.

.Sobre esta tarefa
Operações de gerenciamento de snapshot como atribuição, alteração e exclusão de políticas de snapshot para volumes em um sistema de arquivos FSX for ONTAP são gerenciadas no nível de VM de armazenamento. As políticas de snapshot podem ser compartilhadas com uma única VM de storage ou com todas as VMs de storage.

Algumas tarefas de gerenciamento exigem que você associe um link ao sistema de arquivos FSx para ONTAP . link:https://docs.netapp.com/us-en/workload-fsx-ontap/links-overview.html["Saiba mais sobre os links do Workload Factory"] .

Por padrão, cada volume está associado à política de snapshot do sistema de arquivos `default`. Recomendamos o uso desta política para a maioria das cargas de trabalho.



== Alterar uma política de snapshot

Você pode alterar o nome da política de snapshot, o agendamento e o número de cópias a serem mantidas e ativar ou desativar snapshots imutáveis. Não é possível ativar ou desativar o compartilhamento de políticas entre VMs de armazenamento. Esta opção está disponível apenas durante a criação da política de instantâneos.

.Antes de começar
Para exibir políticas de instantâneo existentes, você deve associar um link. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda como associar um link existente ou criar e associar um novo link"]. Após os associados da ligação, volte a esta operação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em *Armazenamento*, selecione *Ir para Armazenamento*.
. Na aba *FSx para ONTAP*, selecione o menu de ações do sistema de arquivos e então selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Storage VMs*.
. Na guia *VMs de armazenamento*, selecione o menu de ações para a VM de armazenamento que contém o volume a ser protegido com instantâneos agendados, depois *Ações avançadas* e, por fim, *Gerenciar políticas de instantâneos*.
. Na página Gerenciamento de política de snapshot, selecione o menu de ações para alterar a política de snapshot e selecione *Editar*.
. Na caixa de diálogo Editar política de instantâneos, faça as alterações necessárias à política de instantâneos.
. Selecione *aplicar*.


.Resultado
A política de instantâneos é atualizada.



== Ativar instantâneos imutáveis

Bloqueie instantâneos para evitar que sejam excluídos durante o período de retenção.

.Antes de começar
Você deve associar um link para habilitar snapshots imutáveis. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda como associar um link existente ou criar e associar um novo link"]. Após os associados da ligação, volte a esta operação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em *Armazenamento*, selecione *Ir para Armazenamento*.
. Na aba *FSx para ONTAP*, selecione o menu de ações do sistema de arquivos que contém o volume para bloquear snapshots e então selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. Na aba *Volumes*, selecione o botão de ação do volume a ser protegido.
. Selecione *ações de proteção de dados*, *Snapshots* e, em seguida, *tornar um snapshot imutável*.
. Na caixa de diálogo tornar um instantâneo imutável, faça o seguinte:
+
.. *Nome do instantâneo*: Selecione o instantâneo a bloquear.
.. Defina o *período de retenção* em número de horas, dias, meses ou anos.
.. Aceite a declaração.


. Selecione *aplicar*.


.Resultado
O instantâneo do volume está agora bloqueado.



== Atribua uma política de snapshot a um volume

Você pode atribuir uma política de snapshot a um único volume para criar snapshots programados para o volume.

.Antes de começar
Você deve associar um link para atribuir uma política de instantâneo. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda como associar um link existente ou criar e associar um novo link"]. Após os associados da ligação, volte a esta operação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em *Armazenamento*, selecione *Ir para Armazenamento*.
. Na guia *FSx para ONTAP*, selecione o menu de ações do sistema de arquivos que contém o volume ao qual atribuir uma política de snapshot e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Storage VMs*.
. Na guia *VMs de armazenamento*, selecione o menu de ações para a VM de armazenamento que contém o volume a ser protegido com instantâneos agendados, depois *Ações avançadas* e, por fim, *Gerenciar políticas de instantâneos*.
. Na página Gerenciamento de política de instantâneo, selecione o menu de ações da política de instantâneo e, em seguida, selecione *Atribuir política ao volume*.
. Na caixa de diálogo atribuir política de instantâneos, selecione uma política de instantâneos a atribuir ao volume e reveja a programação da política.
+
Se a política contiver snapshots imutáveis e você quiser usá-la, aceite a declaração.

. Selecione *Assign*.


.Resultado
A política de instantâneos é atribuída ao volume.



== Remover uma política de snapshot de um volume

Remover uma política de snapshot de um volume porque você não deseja mais snapshots do volume ou porque deseja excluir uma política de snapshot atribuída a vários volumes. Para <<Eliminar uma política de instantâneos,eliminar uma política de instantâneos>> isso é atribuído a mais de um volume, você deve removê-lo manualmente de todos os volumes.

.Antes de começar
Você deve associar um link para remover uma política de instantâneo. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda como associar um link existente ou criar e associar um novo link"]. Após os associados da ligação, volte a esta operação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em *Armazenamento*, selecione *Ir para Armazenamento*.
. Na guia *FSx para ONTAP*, selecione o menu de ações do sistema de arquivos que contém o volume ao qual atribuir uma política de snapshot e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Storage VMs*.
. Na guia *VMs de armazenamento*, selecione o menu de ações para a VM de armazenamento que contém o volume a ser protegido com instantâneos agendados, depois *Ações avançadas* e, por fim, *Gerenciar políticas de instantâneos*.
. Na página Gerenciamento de política de instantâneo, selecione o menu de ações da política de instantâneo e, em seguida, selecione *Atribuir política ao volume*.
. Na caixa de diálogo atribuir política de instantâneos, selecione *nenhum* para remover a política de instantâneos.
. Selecione *Assign*.


.Resultado
A política de instantâneos é removida do volume.



== Eliminar uma política de instantâneos

Exclua uma política de snapshot quando você não precisar mais dela.

Quando uma política de snapshot é atribuída a mais de um volume, você deve manualmente <<Remover uma política de snapshot de um volume,retire-o.>> de todos os volumes para excluir a política de snapshot. Alternativamente, você pode <<Atribua uma política de snapshot a um volume,atribua uma política de snapshot diferente>> para os volumes.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em *Armazenamento*, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos com o volume e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Storage VMs*.
. Na guia *VMs de armazenamento*, selecione o menu de ações da VM de armazenamento com a política de snapshot a ser excluída, depois *Ações avançadas* e, por fim, *Gerenciar políticas de snapshot*.
. Na página Gerenciamento de política de snapshot, selecione o menu de ações da política de snapshot a ser excluída e selecione *Excluir*.
. Na caixa de diálogo Excluir, selecione *Excluir* para excluir a política.

