---
sidebar: sidebar 
permalink: manage-cifs-share.html 
keywords: cifs, CIFS, cifs share, change cifs share, update cifs share, modify cifs share 
summary: Altere o compartilhamento CIFS de um volume na fábrica de workloads do BlueXP  que usa o tipo de protocolo SMB/CIFS. 
---
= Gerencie o compartilhamento CIFS de um volume de workloads da BlueXP  de fábrica
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
O gerenciamento do compartilhamento CIFS de um volume na fábrica de cargas de trabalho do BlueXP  envolve determinar os usuários e grupos a serem acessados e o tipo de acesso a eles.

.Antes de começar
Determine os usuários ou grupos a dar acesso e o tipo de acesso a eles.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos com o volume a ser atualizado e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. No separador volumes, selecione o menu de três pontos do volume para o qual pretende alterar a partilha SMB.
. Selecione *ações avançadas* e, em seguida, *Editar compartilhamento CIFS*.
. Na página Editar compartilhamento CIFS, forneça o seguinte:
+
.. *Nome*: Insira o nome do compartilhamento CIFS.
.. *Permissões*: Selecione Controle completo, leitura/gravação, leitura ou sem acesso e insira os usuários ou grupos separados por ponto e vírgula ( ; ). Usuários ou grupos são sensíveis a maiúsculas e minúsculas e o domínio do usuário deve ser incluído usando o formato "domínio/nome de usuário".


. Selecione aplicar.
+
As alterações podem fazer com que os usuários ou grupos atuais percam o acesso ao compartilhamento CIFS.

. Selecione *continuar* para salvar as alterações.


.Resultado
São aplicadas alterações ao compartilhamento CIFS.
