---
sidebar: sidebar 
permalink: manage-immutable-files.html 
keywords: enable immutable files, disable immutable files, lock files, unlock files 
summary: Você pode atualizar certas configurações de arquivos imutáveis quando o recurso estiver ativado. 
---
= Gerencie arquivos imutáveis para um volume na fábrica de carga de trabalho do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Você pode atualizar certas configurações de arquivos imutáveis para um volume quando o recurso estiver ativado, como a política de retenção e os períodos, o período de confirmação automática e o modo de adição de volume.

Observe que a ativação de arquivos imutáveis só é possível durante link:create-volume.html["criação de volume"]o .

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Selecione a guia *volumes*.
. Na guia volumes, selecione o menu de três pontos do volume a ser clonado.
. Selecione *ações de proteção de dados* e, em seguida, *Gerenciar arquivos imutáveis*.
. Na página Gerenciar arquivos immutáveis, você pode atualizar o seguinte:
+
** *Período de retenção*: Selecione *não especificado* ou *especificar período*.
+
*** *Não especificado*: O período mínimo padrão é "0" anos e o período máximo padrão é "30 anos".
*** *Especificar período*: Opção para definir a política de retenção, os períodos mínimo e máximo, o recurso de confirmação automática e o recurso de modo de adição de volume. Forneça os seguintes detalhes:
+
**** *Política de retenção*: Este período deve ser maior ou igual ao período mínimo de retenção e menor ou igual ao período máximo de retenção.
**** *Períodos mínimo e máximo*: Defina os períodos mínimo e máximo para confirmar arquivos neste volume para um estado WORM imutável.




** *AUTOCOMMIT*: Ative ou desative o recurso para enviar automaticamente arquivos para WORM que não foram modificados durante o período AUTOCOMMIT.
** *Modo de adição de volume*: Ative ou desative o recurso. Ativar o modo de adição de volume permite adicionar novo conteúdo a arquivos WORM.


. Clique em *aplicar*.


.Resultado
As atualizações agora se aplicam ao volume.
