---
sidebar: sidebar 
permalink: manage-svm-tags.html 
keywords: edit storage vm tags, vm tags, svm tags 
summary: Adicione, atualize ou remova tags de VM de armazenamento para uma VM de armazenamento a qualquer momento. 
---
= Gerenciar tags de VM de armazenamento no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
As tags podem ajudar você a categorizar seus recursos.  Você pode adicionar, editar e remover tags de uma VM de armazenamento a qualquer momento no NetApp Workload Factory.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos com a VM de armazenamento a ser atualizada e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos em VMs de armazenamento, selecione *Gerenciar*.
. Na tela Gerenciar VMs de armazenamento, selecione o menu de ações da VM de armazenamento para a qual deseja editar as tags e, em seguida, selecione *Ações básicas* > *Editar tags da VM de armazenamento*.
. Na página Editar tags de VM de armazenamento, adicione, edite ou remova tags.
+
O número máximo de tags que você pode aplicar a uma VM de armazenamento é 50.

. Selecione *aplicar*.

