---
sidebar: sidebar 
permalink: pause-resume-replication.html 
keywords: pause replication, quiesce replication, resume replication 
summary: Pausar e retomar uma relação de replicação para que o volume de destino se torne o volume de origem. 
---
= Faça uma pausa e retome uma relação de replicação na fábrica do workload do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Pausar uma relação de replicação para interromper as atualizações de replicação agendadas do volume de origem para o volume de destino. O volume de destino passa de somente leitura para leitura e gravação. Ambos os volumes continuam a compartilhar o snapshot de replicação mais recente como uma nova linha de base para ressincronização posterior.

.Sobre esta tarefa
Quando pausada, a relação de replicação entre o volume de origem e o volume de destino continua a existir. As transferências de dados são interrompidas e os volumes se tornam independentes. Para reativar a transferência de alterações do volume de origem para o volume de destino, retome a replicação.

Quando você retoma uma replicação, todas as alterações no volume de destino são desfeitas e o workload do BlueXP  rehabilita a replicação de fábrica. O volume de destino faz a transição de leitura-gravação para somente leitura e recebe atualizações do volume de origem no intervalo de replicação programado novamente. Quando você retoma uma relação de replicação, o volume de destino volta para o instantâneo de replicação inicial mais recente, momento em que o processo de replicação de volume termina.

.Antes de começar
Se você pausar quando uma transferência estiver em andamento, a transferência não será afetada e a relação se tornará "Quiescente" até que a transferência seja concluída. Se a transferência atual for cancelada, será agora uma transferência futura e não será reiniciada.



== Pausar uma relação de replicação

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos a ser atualizado e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *relacionamentos de replicação*.
. Na guia relacionamentos de replicação, selecione o menu de três pontos da relação de replicação a ser pausada.
. Selecione *Pausa (quiesce)*.
. Na caixa de diálogo *quiesce relation*, selecione *quiesce*.


.Resultado
A relação pausa e seu status é exibido como "Pausado".



== Retomar uma relação de replicação em pausa

Quando você retoma uma relação de replicação, todas as alterações no volume de destino enquanto a replicação foi interrompida são excluídas.


NOTE: Os dados gravados no volume de origem original entre a última replicação de dados e a hora em que o volume de origem é desativado não são preservados.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos a ser atualizado e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *relacionamentos de replicação*.
. Na guia relacionamentos de replicação, selecione o menu de três pontos da relação de replicação a ser retomada.
. Selecione *Resume*.
. Na caixa de diálogo Retomar relacionamento, selecione *Resume*.


.Resultado
O relacionamento é retomado e seu status é exibido como "replicado".
