---
settings:
  name: Amazon FSx for NetApp ONTAP
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  release_notes_autogen:
    release_notes_repo: workload-relnotes
  langs: pt-br,us-en,de-de,es-es,fr-fr,it-it,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos do Amazon FSX para NetApp ONTAP
    url: "/index.html"
  - title: Notas de lançamento
    entries:
    - title: O que há de novo
      url: "/whats-new.html"
    - title: Limitações conhecidas
      url: "/known-limitations.html"
  - title: Comece agora
    entries:
    - title: Saiba mais sobre o Amazon FSX for NetApp ONTAP
      url: "/learn-fsx-ontap.html"
    - title: Início rápido
      url: "/quick-start.html"
  - title: Use o Amazon FSX para NetApp ONTAP
    entries:
    - title: Explore as poupanças
      url: "/explore-savings.html"
    - title: Criar recursos de storage
      entries:
      - title: Crie um sistema de arquivos FSX for ONTAP
        url: "/create-file-system.html"
      - title: Crie uma VM de storage
        url: "/create-storage-vm.html"
      - title: Crie um volume
        url: "/create-volume.html"
      - title: Crie um igroup
        url: "/create-igroup.html"
      - title: Criar um dispositivo de bloco
        url: "/create-block-device.html"
    - title: Saiba mais sobre links
      url: "/learn-about-links.html"
    - title: Descubra e visualize volumes de cache
      url: "/discover-cache-volumes.html"
    - title: Acesse seus dados
      url: "/access-data.html"
  - title: Proteja seus dados
    entries:
    - title: Visão geral da proteção de dados
      url: "/data-protection-overview.html"
    - title: Use snapshots para proteger dados
      entries:
      - title: Use snapshots para proteger dados
        url: "/use-snapshots.html"
      - title: Gerenciar políticas de snapshot
        url: "/manage-snapshot-policy.html"
      - title: Gerenciar snapshots
        url: "/manage-snapshots.html"
    - title: Use backups para armazenamento de objetos
      url: "/use-backups.html"
    - title: Use a replicação para proteger os dados
      entries:
      - title: Replique dados
        url: "/create-replication.html"
      - title: Replicar os dados ONTAP locais para o FSx para ONTAP
        url: "/use-onprem-data.html"
      - title: Replique uma VM de storage para outro sistema de arquivos
        url: "/replicate-svm-to-file-system.html"
      - title: Acompanhe atrasos na replicação
        url: "/track-replication-delays.html"
      - title: Gerenciar relações de replicação
        url: "/manage-replication.html"
    - title: Proteja os dados com a proteção Autonomous ransomware
      url: "/ransomware-protection.html"
    - title: Clonar um volume
      url: "/clone-volume.html"
    - title: Crie um cofre cibernético para proteger seus dados.
      url: "/create-cyber-vault.html"
  - title: Gerencie o FSx para ONTAP no Workload Factory
    entries:
    - title: Analisar eventos FSx para ONTAP EMS
      url: "/analyze-events.html"
    - title: Implementar as práticas recomendadas do sistema de arquivos
      entries:
      - title: Análise de configuração do FSX for ONTAP
        url: "/configuration-analysis.html"
      - title: Implemente configurações de sistema de arquivos bem arquitetadas
        url: "/improve-configurations.html"
    - title: Monitore e analise os custos do FSx para ONTAP.
      url: "/track-costs.html"
    - title: Gerenciar volumes
      entries:
      - title: Gerenciar capacidade de volume
        url: "/manage-volume-capacity.html"
      - title: Defina os limites de latência de volume
        url: "/set-volume-latency-thresholds.html"
      - title: Gerenciar configurações de volume
        url: "/manage-volume-settings.html"
      - title: Gerenciar volumes de cache
        url: "/manage-cache-volumes.html"
      - title: Alterar uma política de disposição em camadas
        url: "/change-tiering-policy.html"
      - title: Gerenciar políticas de exportação de NFS
        url: "/manage-nfs-export-policy.html"
      - title: Gerenciar compartilhamentos SMB/CIFS
        url: "/manage-cifs-share.html"
      - title: Gerenciar pontos de acesso S3
        entries:
        - title: Criar e associar pontos de acesso S3
          url: "/create-s3-access-points.html"
        - title: Editar pontos de acesso S3
          url: "/edit-s3-access-points.html"
        - title: Configure a infraestrutura da tabela de diários
          url: "/setup-journal-table.html"
        - title: Veja detalhes sobre os pontos de acesso S3
          url: "/view-s3-details.html"
        - title: Excluir pontos de acesso S3
          url: "/delete-s3-access-points.html"
      - title: Divida um volume clonado
        url: "/split-cloned-volume.html"
      - title: Eliminar um volume
        url: "/delete-volume.html"
    - title: Gerenciar storage em bloco
      entries:
      - title: Gerenciar storage em bloco
        url: "/manage-block-storage.html"
      - title: Aplicar tags a dispositivos de bloco
        url: "/apply-block-device-tags.html"
    - title: Gerencie sistemas de arquivos
      entries:
      - title: Ajustar a capacidade do sistema de arquivos
        url: "/adjust-file-system-capacity.html"
      - title: Gerencie as configurações do sistema de arquivos
        url: "/manage-file-system-settings.html"
      - title: Provisione IOPS para um sistema de arquivos
        url: "/provision-iops.html"
      - title: Eliminar um sistema de ficheiros
        url: "/delete-file-system.html"
    - title: Gerencie VMs de armazenamento
      entries:
      - title: Gerencie as configurações da VM de armazenamento
        url: "/manage-svm-settings.html"
      - title: Exclua uma VM de armazenamento
        url: "/delete-svm.html"
    - title: Monitore as operações com o Tracker
      url: "/monitor-operations.html"
  - title: Referência
    entries:
    - title: Desempenho do FSX para ONTAP
      url: "/performance-reference.html"
    - title: Segurança para o FSX for ONTAP
      url: "/security-reference.html"
  - title: Conhecimento e apoio
    entries:
    - title: Registre-se para obter suporte
      url: "/support-registration.html"
    - title: Obtenha ajuda
      url: "/get-help.html"
  - title: Avisos legais
    url: "/legal-notices.html"
product-family:
  name: NetApp Workload Factory
  repo: workload-family
