---
sidebar: sidebar 
permalink: provision-iops.html 
keywords: iops, SSD, provision, allocate 
summary: Provisione ou provisione manualmente o IOPS SSD para um sistema de arquivos FSX for ONTAP. 
---
= Provisione IOPS SSD para um sistema de arquivos FSX for ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Provisione automaticamente ou manualmente IOPS SSD para um sistema de arquivos FSx para ONTAP no NetApp Workload Factory.

.Sobre esta tarefa
Você pode ativar o provisionamento automático de IOPS SSD para um sistema de arquivos FSX ou provisionar manualmente IOPS.

IOPS provisionadas automaticamente são calculadas como três IOPS por GiB.

Se você provisionar manualmente o IOPS, talvez seja necessário aumentar o IOPS antes link:increase-file-system-capacity.html["aumento da capacidade do sistema de arquivos"]do .

Para obter informações sobre os limites de IOPS, consulte a link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Quotas"^]documentação do AWS FSX for NetApp ONTAP.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos para provisionar IOPS e, em seguida, selecione *Gerenciar*.
. Em informações, selecione o ícone de lápis que aparece ao lado da seta suspensa quando o Mouse passa sobre a linha *Alocação de IOPS*.
. Na caixa de diálogo IOPS provisionado, selecione *Automático* ou *fornecido pelo usuário*.
. Se você selecionar *User provisioned*, digite o valor *IOPS* desejado.
. Selecione *aplicar*.

