---
sidebar: sidebar 
permalink: replicate-svm-to-file-system.html 
keywords:  
summary: Replicar uma VM de armazenamento para outro sistema de arquivos do FSX for ONTAP fornece uma camada protetora de acesso a dados em caso de perda de dados. 
---
= Replique uma VM de armazenamento para outro sistema de arquivos FSX for ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
A replicação de uma VM de armazenamento para outro sistema de arquivos FSx for ONTAP no NetApp Workload Factory fornece uma camada protetora de acesso a dados em caso de perda de dados.  Esta operação replica todos os volumes em uma VM de armazenamento para outro FSx para o sistema de arquivos ONTAP .

.Antes de começar
Para replicar uma VM de armazenamento para outro sistema de arquivos FSx for ONTAP, você deve associar um link. link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Aprenda como associar um link existente ou criar e associar um novo link"]. Após os associados da ligação, volte a esta operação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos com a VM de armazenamento a ser replicada e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos em VMs de armazenamento, selecione *Gerenciar*.
. Na tela Gerenciar VMs de armazenamento, selecione o menu de ações da VM de armazenamento para a qual deseja replicar uma SVM e, em seguida, selecione *Ações avançadas* > *Replicar VM de armazenamento*.
. Na página replicar dados, em destino replicação, forneça o seguinte:
+
.. *FSX para sistema de arquivos ONTAP*: Selecione credenciais, região e nome do sistema de arquivos FSX for ONTAP para o sistema de arquivos FSX for ONTAP de destino.
.. *Nome da VM de armazenamento*: Selecione a VM de armazenamento no menu suspenso.
.. *Nome do volume*: O nome do volume de destino é gerado automaticamente com o seguinte `{OriginalVolumeName}_copy` formato .
.. *Política de disposição em categorias*: Selecione a política de disposição em categorias para os dados armazenados no volume de destino.
+
_Auto_ é a política de camadas padrão ao criar um volume usando a interface de usuário do Workload Factory FSx para ONTAP .  Para obter mais informações sobre políticas de níveis de volume, consultelink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidade de armazenamento de volume"^] na documentação do AWS FSx para NetApp ONTAP .

.. *Taxa máxima de transferência*: Selecione *limitada* e insira o limite máximo de transferência em MB/s. Em alternativa, selecione *Unlimited*.
+
Sem um limite, o desempenho da rede e do aplicativo pode declinar. Como alternativa, recomendamos uma taxa de transferência ilimitada para os sistemas de arquivos FSX for ONTAP para cargas de trabalho críticas, por exemplo, aquelas que são usadas principalmente para recuperação de desastres.



. Em Configurações de replicação, forneça o seguinte:
+
.. *Intervalo de replicação*: Selecione a frequência em que os instantâneos são transferidos do volume de origem para o volume de destino.
.. *Retenção de longo prazo*: Opcionalmente, habilite snapshots para retenção de longo prazo.
+
Se você habilitar a retenção a longo prazo, selecione uma política existente ou crie uma nova política para definir os snapshots a serem replicados e o número a ser retido.

+
... Para *escolha uma política existente*, selecione uma política existente no menu suspenso.
... Para *criar uma nova política*, forneça o seguinte:
+
.... *Nome da política*: Insira um nome de política.
.... *Políticas de snapshot*: Na tabela, selecione a frequência da política de snapshot e o número de cópias a reter. Pode selecionar mais de uma política de instantâneos.






. Selecione *criar*.


.Resultado
Todos os volumes dentro da VM de storage são replicados para o sistema de arquivos de destino.
