---
sidebar: sidebar 
permalink: replicate-svm-to-file-system.html 
keywords:  
summary: Replicar uma VM de armazenamento para outro sistema de arquivos do FSX for ONTAP fornece uma camada protetora de acesso a dados em caso de perda de dados. 
---
= Replique uma VM de armazenamento para outro sistema de arquivos FSX for ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
A replicação de uma VM de armazenamento para outro sistema de arquivos do FSX for ONTAP na fábrica de cargas de trabalho do BlueXP  fornece uma camada protetora de acesso a dados em caso de perda de dados. Essa operação replica todos os volumes em uma VM de armazenamento para outro sistema de arquivos do FSX for ONTAP.

.Antes de começar
Para replicar uma VM de armazenamento para outro sistema de arquivos do FSX for ONTAP, você deve link:manage-links.html["associe um link"]. Se você não tiver um link existente, link:create-link.html["crie um link"]. Para associar um link no sistema de arquivos, selecione *associar link* sob *nome da conta*. Assim que o link se associar, volte a esta operação.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos com a VM de armazenamento para replicar e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *Storage VMs*.
. Na guia Storage VMs (VMs de armazenamento), selecione o menu de três pontos da VM de armazenamento para o qual replicar uma SVM.
. Selecione *Replique storage VM*.
. Na página criar replicação, em destino replicação, forneça o seguinte:
+
.. *FSX para sistema de arquivos ONTAP*: Selecione credenciais, região e nome do sistema de arquivos FSX for ONTAP para o sistema de arquivos FSX for ONTAP de destino.
.. *Nome da VM de armazenamento*: Selecione a VM de armazenamento no menu suspenso.
.. *Nome do volume*: O nome do volume de destino é gerado automaticamente com o seguinte `{OriginalVolumeName}_copy` formato .
.. *Política de disposição em categorias*: Selecione a política de disposição em categorias para os dados armazenados no volume de destino.
+
_Auto_ é a política de disposição em camadas padrão ao criar um volume usando a interface de usuário do FSX for ONTAP de fábrica de carga de trabalho. Para obter mais informações sobre políticas de disposição em camadas de volume, consulte a link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/volume-storage-capacity.html#data-tiering-policy["Capacidade de armazenamento de volume"^]documentação do AWS FSX for NetApp ONTAP.

.. *Taxa máxima de transferência*: Selecione *limitada* e insira o limite máximo de transferência em MB/s. Em alternativa, selecione *Unlimited*.
+
Sem um limite, o desempenho da rede e do aplicativo pode declinar. Como alternativa, recomendamos uma taxa de transferência ilimitada para os sistemas de arquivos FSX for ONTAP para cargas de trabalho críticas, por exemplo, aquelas que são usadas principalmente para recuperação de desastres.



. Em Configurações de replicação, forneça o seguinte:
+
.. *Intervalo de replicação*: Selecione a frequência em que os instantâneos são transferidos do volume de origem para o volume de destino.
.. *Retenção de longo prazo*: Opcionalmente, habilite snapshots para retenção de longo prazo.
+
Se você habilitar a retenção a longo prazo, selecione uma política existente ou crie uma nova política para definir os snapshots a serem replicados e o número a ser retido.

+
... Para *escolha uma política existente*, selecione uma política existente no menu suspenso.
... Para *criar uma nova política*, forneça o seguinte:
+
.... *Nome da política*: Insira um nome de política.
.... *Políticas de snapshot*: Na tabela, selecione a frequência da política de snapshot e o número de cópias a reter. Pode selecionar mais de uma política de instantâneos.






. Selecione *criar*.


.Resultado
Todos os volumes dentro da VM de storage são replicados para o sistema de arquivos de destino.
