---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: Redefina a senha de uma VM de armazenamento no NetApp Workload Factory quando necessário. 
---
= Redefinir a senha da VM de armazenamento no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Redefina a senha de uma VM de armazenamento no NetApp Workload Factory quando necessário.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos com a senha da VM de armazenamento que deseja redefinir e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos em VMs de armazenamento, selecione *Gerenciar*.
. Na tela Gerenciar VMs de armazenamento, selecione o menu de ações da VM de armazenamento para a qual deseja redefinir a senha e, em seguida, selecione *Ações básicas* > *Redefinir senha*.
. Na caixa de diálogo Redefinir senha, forneça o seguinte:
+
.. *Nova senha*: Insira uma nova senha para a VM de armazenamento.
.. *Confirm password*: Digite a nova senha novamente para confirmar.


. Selecione *aplicar*.

