---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: Redefina a senha da VM de armazenamento quando necessário. 
---
= Redefina a senha de uma VM de armazenamento
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Redefina a senha da VM de armazenamento quando necessário.

.Passos
. Inicie sessão no link:https://console.workloads.netapp.com/["Console de fábrica da carga de trabalho"^]
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos FSX for ONTAP com a VM de armazenamento para atualizar e selecione *Gerenciar*.
. Na guia Visão geral do sistema de arquivos, selecione a guia *Storage VMs*.
. Na guia Storage VMs (VMs de armazenamento), selecione o menu Three DOTS (três pontos) da VM de armazenamento para o qual redefinir a senha.
. Selecione *Redefinir senha*.
. Na caixa de diálogo Redefinir senha, forneça o seguinte:
+
.. *Nova senha*: Insira uma nova senha para a VM de armazenamento.
.. *Confirm password*: Digite a nova senha novamente para confirmar.


. Clique em *aplicar*.

