---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: Redefina a senha de uma VM de armazenamento no NetApp Workload Factory quando necessário. 
---
= Redefinir a senha da VM de armazenamento no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Redefina a senha de uma VM de armazenamento no NetApp Workload Factory quando necessário.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos FSx for ONTAP com a VM de armazenamento a ser atualizada e, em seguida, selecione *Gerenciar*.
. Na guia Visão geral do sistema de arquivos, selecione a guia *Storage VMs*.
. Na guia VMs de armazenamento, selecione o menu de ações da VM de armazenamento para redefinir a senha.
. Selecione *Redefinir senha*.
. Na caixa de diálogo Redefinir senha, forneça o seguinte:
+
.. *Nova senha*: Insira uma nova senha para a VM de armazenamento.
.. *Confirm password*: Digite a nova senha novamente para confirmar.


. Selecione *aplicar*.

