---
sidebar: sidebar 
permalink: reset-svm-password.html 
keywords: reset storage vm password, reset svm password 
summary: Redefina a senha de uma VM de armazenamento na fábrica de carga de trabalho do BlueXP , quando necessário. 
---
= Redefina a senha da VM de armazenamento na fábrica da carga de trabalho do BlueXP 
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Redefina a senha de uma VM de armazenamento na fábrica de carga de trabalho do BlueXP , quando necessário.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos FSX for ONTAP com a VM de armazenamento para atualizar e selecione *Gerenciar*.
. Na guia Visão geral do sistema de arquivos, selecione a guia *Storage VMs*.
. Na guia Storage VMs (VMs de armazenamento), selecione o menu de três pontos da VM de armazenamento para o qual redefinir a senha.
. Selecione *Redefinir senha*.
. Na caixa de diálogo Redefinir senha, forneça o seguinte:
+
.. *Nova senha*: Insira uma nova senha para a VM de armazenamento.
.. *Confirm password*: Digite a nova senha novamente para confirmar.


. Selecione *aplicar*.

