---
sidebar: sidebar 
permalink: restore-from-backup.html 
keywords: restore backup, new volume, volume restoration, backup 
summary: Restaure um volume de um backup para qualquer sistema de arquivos do FSX for ONTAP na sua conta da AWS. 
---
= Restaurar um volume de um backup no workload do BlueXP  de fábrica
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Na fábrica de carga de trabalho do BlueXP , você pode restaurar um volume de um backup para qualquer sistema de arquivos do FSX for ONTAP na sua conta da AWS.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, selecione o menu de três pontos do sistema de arquivos com o volume e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. No separador *volumes*, selecione o menu de três pontos para o volume a restaurar a partir de uma cópia de segurança.
. Selecione *ações de proteção de dados*, *FSX for ONTAP backup* e, em seguida, *Restaurar a partir de um backup*.
. Na caixa de diálogo Restaurar a partir de uma cópia de segurança, forneça o seguinte:
+
.. * Sistema de arquivos de destino*: Selecione o sistema de arquivos de destino no menu suspenso.
.. *Target storage VM*: Selecione a VM de armazenamento de destino no menu suspenso.
.. *Nome da cópia de segurança*: Selecione o nome da cópia de segurança no menu pendente.
.. *Nome do volume restaurado*: Insira o nome do volume restaurado.


. Selecione *Restaurar*.

