---
sidebar: sidebar 
permalink: restore-from-backup.html 
keywords: restore backup, new volume, volume restoration, backup 
summary: Restaure um volume de um backup para qualquer sistema de arquivos do FSX for ONTAP na sua conta da AWS. 
---
= Restaurar um volume de um backup no NetApp Workload Factory
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
No NetApp Workload Factory, você pode restaurar um volume de um backup para qualquer sistema de arquivos FSx for ONTAP na sua conta da AWS.

A fábrica de carga de trabalho determina se você tem capacidade suficiente para a restauração e pode adicionar automaticamente a capacidade da camada de storage SSD, caso não o faça.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos com o volume e, em seguida, selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. Na aba *Volumes*, selecione o menu de ações para o volume a ser restaurado a partir de um backup.
. Selecione *ações de proteção de dados*, *FSX for ONTAP backup* e, em seguida, *Restaurar a partir de um backup*.
. Na caixa de diálogo Restaurar a partir de uma cópia de segurança, forneça o seguinte:
+
.. * Sistema de arquivos de destino*: Selecione o sistema de arquivos de destino no menu suspenso.
.. *Target storage VM*: Selecione a VM de armazenamento de destino no menu suspenso.
.. *Nome da cópia de segurança*: Selecione o nome da cópia de segurança no menu pendente.
.. *Nome do volume restaurado*: Insira o nome do volume restaurado.


. Verifique a capacidade do sistema de arquivos para a operação de restauração.
+
Quando a capacidade do sistema de arquivos é limitada, pode ocorrer o seguinte:

+
** A restauração pode levar a capacidade utilizada além do limite especificado.  Você pode concluir a operação de restauração.  Considerarlink:increase-file-system-capacity.html["Adicionar manualmente a capacidade da camada de storage SSD"] ou selecionar o Workload Factory para adicionar automaticamente a capacidade do nível de armazenamento SSD.
** A restauração requer capacidade SSD adicional.  Você deve selecionar o Workload Factory para adicionar automaticamente a capacidade de armazenamento SSD para continuar.


. Selecione *Restaurar*.

