---
sidebar: sidebar 
permalink: restore-from-backup.html 
keywords: restore backup, new volume, volume restoration, backup 
summary: Restaure um volume de um backup para qualquer sistema de arquivos do FSX for ONTAP na sua conta da AWS. 
---
= Restaurar um volume a partir de uma cópia de segurança
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Restaure um volume de um backup para qualquer sistema de arquivos do FSX for ONTAP na sua conta da AWS.

.Passos
. Inicie sessão no link:https://console.workloads.netapp.com/["Console de fábrica da carga de trabalho"^]
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, clique no menu de três pontos do sistema de arquivos com o volume e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *volumes*.
. Na guia *volumes*, clique no menu três pontos para o volume restaurar a partir de um backup.
. Selecione *ações de proteção de dados*, *FSX for ONTAP backup* e, em seguida, *Restaurar a partir de um backup*.
. Na caixa de diálogo Restaurar a partir de uma cópia de segurança, forneça o seguinte:
+
.. * Sistema de arquivos de destino*: Selecione o sistema de arquivos de destino no menu suspenso.
.. *Target storage VM*: Selecione a VM de armazenamento de destino no menu suspenso.
.. *Nome da cópia de segurança*: Selecione o nome da cópia de segurança no menu pendente.
.. *Nome do volume restaurado*: Insira o nome do volume restaurado.


. Clique em *Restaurar*.

