---
sidebar: sidebar 
permalink: stop-replication.html 
keywords: stop replication, break replication 
summary: Parar uma relação de replicação entre os volumes de origem e destino. 
---
= Parar uma relação de replicação
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Quando você interrompe uma replicação, a replicação agendada é atualizada do volume de origem para a pausa do volume de destino. O volume de destino passa de somente leitura para leitura e gravação.

.Passos
. Inicie sessão no link:https://console.workloads.netapp.com/["Console de fábrica da carga de trabalho"^]
. Em armazenamento, selecione *ir para inventário de armazenamento*.
. Na guia *FSX for ONTAP*, clique no menu de três pontos do sistema de arquivos para atualizar e selecione *Gerenciar*.
. Na visão geral do sistema de arquivos, selecione a guia *relacionamentos de replicação*.
. Na guia relacionamentos de replicação, clique no menu três pontos da relação de replicação a ser interrompida.
. Selecione *Break*.
. Na caixa de diálogo quebrar replicação, selecione *quebrar*.


O status da replicação do volume muda para *Broken*. O volume de destino torna-se gravável.
