---
sidebar: sidebar 
permalink: update-throughput-capacity.html 
keywords: update throughput, change throughput, throughput capacity 
summary: Atualize a capacidade de transferência de um sistema de arquivos FSx para ONTAP no NetApp Workload Factory conforme necessário. 
---
= Atualize a capacidade de transferência para um sistema de ficheiros
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Atualize a capacidade de transferência de um sistema de arquivos FSx para ONTAP no NetApp Workload Factory conforme necessário.

Para saber os limites de capacidade de taxa de transferência, consulte a link:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/limits.html["Quotas"^]documentação do AWS FSX for NetApp ONTAP.

.Passos
. Inicie sessão utilizando uma das link:https://docs.netapp.com/us-en/workload-setup-admin/console-experiences.html["experiências de console"^].
. No bloco Armazenamento, selecione *Ir para Armazenamento*.
. No menu Armazenamento, selecione *FSx para ONTAP*.
. No *FSx for ONTAP*, selecione o menu de ações do sistema de arquivos para atualizar a capacidade de transferência e, em seguida, selecione *Gerenciar*.
. Em informações, selecione o ícone de lápis ao lado de *capacidade de transferência*. O ícone de lápis aparece ao lado da seta suspensa quando o Mouse passa sobre a linha *capacidade de transferência*.
. Na caixa de diálogo capacidade de throughput, selecione a capacidade de throughput que você precisa.
. Selecione *Apply* para salvar as alterações.

