---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, enhancements, fixes, new features, workload factory, amazon fsx for netapp ontap, fsx for ontap' 
summary: Saiba o que há de novo no Amazon FSX for NetApp ONTAP. 
---
= O que há de novo no Amazon FSX for NetApp ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Saiba o que há de novo no Amazon FSX for NetApp ONTAP.



== 3 de novembro de 2024



=== Vistas de separador no inventário de armazenamento

O inventário de armazenamento foi atualizado para uma vista de duas abas:

* Guia FSX for ONTAP: Exibe os sistemas de arquivos FSX for ONTAP que você tem atualmente.
* Guia economia: Exibe os sistemas de armazenamento Elastic Block Store, FSX for Windows File Server e Elastic File Systems. A partir daí, você pode explorar as economias desses sistemas comparando-os com o FSX for ONTAP.




== 29 de setembro de 2024



=== Atualizações de criação de links

* Visualizador de Codebox: Codebox agora está integrado no processo de criação de links. Você pode exibir e copiar o modelo do CloudFormation do Codebox na fábrica de carga de trabalho antes de redirecionar para a AWS para executar a operação.
* Permissões necessárias: As permissões necessárias para executar a criação de links no AWS CloudFormation agora estão disponíveis para exibir e copiar a partir do assistente criar link na fábrica de cargas de trabalho.
* Suporte para criação manual de links: Esse recurso permite a criação autônoma no AWS CloudFormation com o Registro manual do link ARN. Isso é útil quando uma equipe de segurança ou DevOps auxilia no processo de criação de links.


link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-link.html["Crie um link"]



== 1 de setembro de 2024



=== Suporte de modo de leitura para gerenciamento de armazenamento

O modo de leitura está disponível para gerenciamento de storage na fábrica de carga de trabalho. O modo de leitura melhora a experiência do modo básico adicionando permissões somente leitura para que os modelos de infraestrutura como código sejam preenchidos com suas variáveis específicas. Os modelos de infraestrutura como código podem ser executados diretamente da sua conta da AWS sem fornecer permissões de modificação à fábrica de carga de trabalho.

link:https://docs.netapp.com/us-en/workload-setup-admin/operational-modes.html["Saiba mais sobre o modo de leitura"]



=== Backup antes do suporte à exclusão de volume

Agora você pode fazer backup de um volume antes de excluí-lo. O backup permanecerá no sistema de arquivos até ser excluído.

link:https://docs.netapp.com/us-en/workload-fsx-ontap/delete-volume.html["Eliminar um volume"]



== 4 de agosto de 2024



=== Suporte ao Terraform

Agora você pode usar o Terraform no Codebox para implantar sistemas de arquivos e VMs de armazenamento.

* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-file-system.html["Crie um sistema de arquivos"]
* link:https://docs.netapp.com/us-en/workload-fsx-ontap/create-storage-vm.html["Crie uma VM de storage"]
* link:https://docs.netapp.com/us-en/workload-setup-admin/use-codebox.html["Use o Terraform do Codebox"]




=== Recomendações de taxa de transferência e IOPS na calculadora de armazenamento

A calculadora de armazenamento faz recomendações de configuração do sistema de arquivos FSX for ONTAP para taxa de transferência e IOPS com base nas práticas recomendadas da AWS, que fornece orientação ideal para suas seleções.



== 7 de julho de 2024



=== Lançamento inicial da fábrica de carga de trabalho para o Amazon FSX for NetApp ONTAP

O Amazon FSX for NetApp ONTAP agora está disponível na fábrica de cargas de trabalho do BlueXP .
